# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'arbolBusqueda.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        if not StackedWidget.objectName():
            StackedWidget.setObjectName(u"StackedWidget")
        StackedWidget.resize(761, 521)
        StackedWidget.setStyleSheet(u"background-color:rgb(14, 165, 165)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(160, 30, 461, 91))
        font = QFont()
        font.setFamilies([u"Caprasimo"])
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext = QPushButton(self.page)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(650, 470, 75, 24))
        self.btnNext.setStyleSheet(u"background-color:rgb(31, 90, 85)")
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(290, 280, 191, 181))
        self.label_2.setPixmap(QPixmap(u"Sources/Images/rama.png"))
        self.label_2.setScaledContents(True)
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 140, 671, 121))
        font1 = QFont()
        font1.setFamilies([u"Caprasimo"])
        font1.setPointSize(12)
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_4 = QLabel(self.page_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 140, 671, 121))
        self.label_4.setFont(font1)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_2 = QPushButton(self.page_2)
        self.btnNext_2.setObjectName(u"btnNext_2")
        self.btnNext_2.setGeometry(QRect(650, 470, 75, 24))
        self.btnNext_2.setStyleSheet(u"background-color:rgb(31, 90, 85)")
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(160, 30, 461, 91))
        self.label_5.setFont(font)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(240, 390, 91, 91))
        self.label_6.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(260, 250, 251, 221))
        self.label_7.setPixmap(QPixmap(u"Sources/Images/rama.png"))
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(270, 420, 31, 21))
        font2 = QFont()
        font2.setFamilies([u"Caprasimo"])
        font2.setPointSize(11)
        self.label_8.setFont(font2)
        self.label_8.setStyleSheet(u"background-color:white;color:cblack")
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StackedWidget.addWidget(self.page_2)
        self.label_4.raise_()
        self.btnNext_2.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_9 = QLabel(self.page_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(160, 30, 461, 91))
        self.label_9.setFont(font)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_10 = QLabel(self.page_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 150, 671, 61))
        self.label_10.setFont(font1)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_3 = QPushButton(self.page_3)
        self.btnNext_3.setObjectName(u"btnNext_3")
        self.btnNext_3.setGeometry(QRect(650, 470, 75, 24))
        self.btnNext_3.setStyleSheet(u"background-color:rgb(31, 90, 85)")
        self.label_11 = QLabel(self.page_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 260, 241, 141))
        self.label_11.setFont(font1)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_12 = QLabel(self.page_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(500, 260, 261, 141))
        self.label_12.setFont(font1)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_13 = QLabel(self.page_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(260, 420, 71, 71))
        self.label_13.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_13.setScaledContents(True)
        self.label_14 = QLabel(self.page_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(250, 260, 251, 221))
        self.label_14.setPixmap(QPixmap(u"Sources/Images/rama.png"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.page_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(280, 440, 31, 21))
        self.label_15.setFont(font2)
        self.label_15.setStyleSheet(u"background-color:white;color:cblack")
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(340, 250, 71, 71))
        self.label_16.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.page_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(360, 270, 31, 21))
        self.label_17.setFont(font2)
        self.label_17.setStyleSheet(u"background-color:white;color:cblack")
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_18 = QLabel(self.page_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(450, 380, 31, 21))
        self.label_18.setFont(font2)
        self.label_18.setStyleSheet(u"background-color:white;color:cblack")
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_19 = QLabel(self.page_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(430, 360, 71, 71))
        self.label_19.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_19.setScaledContents(True)
        StackedWidget.addWidget(self.page_3)
        self.label_9.raise_()
        self.label_10.raise_()
        self.btnNext_3.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.label_13.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_19.raise_()
        self.label_18.raise_()
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.btnNext_4 = QPushButton(self.page_4)
        self.btnNext_4.setObjectName(u"btnNext_4")
        self.btnNext_4.setGeometry(QRect(650, 470, 75, 24))
        self.btnNext_4.setStyleSheet(u"background-color:rgb(31, 90, 85)")
        self.label_20 = QLabel(self.page_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(160, 30, 461, 91))
        self.label_20.setFont(font)
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_21 = QLabel(self.page_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(50, 140, 681, 91))
        self.label_21.setFont(font1)
        self.label_21.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_22 = QLabel(self.page_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(260, 350, 191, 161))
        self.label_22.setPixmap(QPixmap(u"Sources/Images/rama.png"))
        self.label_22.setScaledContents(True)
        self.label_23 = QLabel(self.page_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(270, 460, 31, 21))
        self.label_23.setFont(font2)
        self.label_23.setStyleSheet(u"background-color:white;color:cblack")
        self.label_23.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_24 = QLabel(self.page_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(400, 430, 61, 61))
        self.label_24.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_24.setScaledContents(True)
        self.label_25 = QLabel(self.page_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(420, 440, 31, 21))
        self.label_25.setFont(font2)
        self.label_25.setStyleSheet(u"background-color:white;color:cblack")
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_26 = QLabel(self.page_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(350, 340, 31, 21))
        self.label_26.setFont(font2)
        self.label_26.setStyleSheet(u"background-color:white;color:cblack")
        self.label_26.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_27 = QLabel(self.page_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(330, 330, 61, 61))
        self.label_27.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_27.setScaledContents(True)
        self.label_28 = QLabel(self.page_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(250, 450, 61, 61))
        self.label_28.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_28.setScaledContents(True)
        self.label_29 = QLabel(self.page_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(370, 260, 111, 111))
        self.label_29.setPixmap(QPixmap(u"Sources/Images/rama.png"))
        self.label_29.setScaledContents(True)
        self.label_30 = QLabel(self.page_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(410, 250, 51, 51))
        self.label_30.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_30.setScaledContents(True)
        self.label_31 = QLabel(self.page_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(430, 260, 21, 20))
        self.label_31.setFont(font2)
        self.label_31.setStyleSheet(u"background-color:white;color:cblack")
        self.label_31.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StackedWidget.addWidget(self.page_4)
        self.btnNext_4.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_28.raise_()
        self.label_23.raise_()
        self.label_29.raise_()
        self.label_27.raise_()
        self.label_26.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.label_32 = QLabel(self.page_5)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(160, 30, 461, 91))
        self.label_32.setFont(font)
        self.label_32.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_5 = QPushButton(self.page_5)
        self.btnNext_5.setObjectName(u"btnNext_5")
        self.btnNext_5.setGeometry(QRect(650, 470, 75, 24))
        self.btnNext_5.setStyleSheet(u"background-color:rgb(31, 90, 85)")
        self.label_33 = QLabel(self.page_5)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(40, 140, 681, 91))
        self.label_33.setFont(font1)
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_34 = QLabel(self.page_5)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(70, 290, 201, 91))
        self.label_34.setFont(font1)
        self.label_34.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_35 = QLabel(self.page_5)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(260, 350, 191, 161))
        self.label_35.setPixmap(QPixmap(u"Sources/Images/rama.png"))
        self.label_35.setScaledContents(True)
        self.label_36 = QLabel(self.page_5)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(440, 250, 21, 20))
        self.label_36.setFont(font2)
        self.label_36.setStyleSheet(u"background-color:white;color:cblack")
        self.label_36.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_37 = QLabel(self.page_5)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(410, 440, 31, 21))
        self.label_37.setFont(font2)
        self.label_37.setStyleSheet(u"background-color:white;color:cblack")
        self.label_37.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_38 = QLabel(self.page_5)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(330, 330, 61, 61))
        self.label_38.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_38.setScaledContents(True)
        self.label_39 = QLabel(self.page_5)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(270, 460, 31, 21))
        self.label_39.setFont(font2)
        self.label_39.setStyleSheet(u"background-color:white;color:cblack")
        self.label_39.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_40 = QLabel(self.page_5)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(390, 430, 61, 61))
        self.label_40.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_40.setScaledContents(True)
        self.label_41 = QLabel(self.page_5)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(370, 260, 111, 111))
        self.label_41.setPixmap(QPixmap(u"Sources/Images/rama.png"))
        self.label_41.setScaledContents(True)
        self.label_42 = QLabel(self.page_5)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(420, 240, 51, 51))
        self.label_42.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_42.setScaledContents(True)
        self.label_43 = QLabel(self.page_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(250, 450, 61, 61))
        self.label_43.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_43.setScaledContents(True)
        self.label_44 = QLabel(self.page_5)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(350, 340, 31, 21))
        self.label_44.setFont(font2)
        self.label_44.setStyleSheet(u"background-color:white;color:cblack")
        self.label_44.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_45 = QLabel(self.page_5)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(520, 340, 201, 91))
        self.label_45.setFont(font1)
        self.label_45.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_46 = QLabel(self.page_5)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(530, 240, 151, 81))
        self.label_46.setFont(font1)
        self.label_46.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_47 = QLabel(self.page_5)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(30, 380, 261, 51))
        self.label_47.setFont(font1)
        self.label_47.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StackedWidget.addWidget(self.page_5)
        self.label_41.raise_()
        self.label_35.raise_()
        self.label_43.raise_()
        self.label_32.raise_()
        self.btnNext_5.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.label_44.raise_()
        self.label_42.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_45.raise_()
        self.label_46.raise_()
        self.label_47.raise_()
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.btnNext_6 = QPushButton(self.page_6)
        self.btnNext_6.setObjectName(u"btnNext_6")
        self.btnNext_6.setGeometry(QRect(300, 330, 171, 81))
        font3 = QFont()
        font3.setFamilies([u"Caprasimo"])
        font3.setPointSize(14)
        self.btnNext_6.setFont(font3)
        self.btnNext_6.setStyleSheet(u"background-color:rgb(31, 90, 85)")
        self.label_48 = QLabel(self.page_6)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(160, 30, 461, 91))
        self.label_48.setFont(font)
        self.label_48.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_49 = QLabel(self.page_6)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(50, 160, 681, 111))
        font4 = QFont()
        font4.setFamilies([u"Caprasimo"])
        font4.setPointSize(16)
        self.label_49.setFont(font4)
        self.label_49.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_50 = QLabel(self.page_6)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(90, 290, 151, 161))
        self.label_50.setPixmap(QPixmap(u"Sources/Images/arbol2.png"))
        self.label_50.setScaledContents(True)
        self.label_51 = QLabel(self.page_6)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(550, 290, 141, 151))
        self.label_51.setPixmap(QPixmap(u"Sources/Images/rama.png"))
        self.label_51.setScaledContents(True)
        StackedWidget.addWidget(self.page_6)

        self.retranslateUi(StackedWidget)

        StackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(StackedWidget)
    # setupUi

    def retranslateUi(self, StackedWidget):
        StackedWidget.setWindowTitle(QCoreApplication.translate("StackedWidget", u"StackedWidget", None))
        self.label.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES BINARIOS\n"
"DE BUSQUEDA", None))
        self.btnNext.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_2.setText("")
        self.label_3.setText(QCoreApplication.translate("StackedWidget", u"Imagina que tienes un \u00e1rbol muy especial en tu jard\u00edn. \n"
"No da manzanas ni peras, \u00a1da libros m\u00e1gicos! \n"
"Cada libro tiene un n\u00famero en su portada, y este \u00e1rbol sabe \n"
"exactamente d\u00f3nde colocar cada uno para que siempre los encuentres f\u00e1cilmente. \n"
"Este \u00e1rbol m\u00e1gico es nuestro \u00c1rbol Binario de B\u00fasqueda.", None))
        self.label_4.setText(QCoreApplication.translate("StackedWidget", u"El Tronco Principal (la Ra\u00edz): Todo el \u00e1rbol empieza con un tronco principal fuerte, \n"
"el m\u00e1s grueso. Este tronco es el primer libro que colocamos, \n"
"el libro gu\u00eda que nos ayuda a empezar a buscar cualquier otro libro en el \u00e1rbol.\n"
"La ra\u00edz de nuestro arb\u00f3l sera el n\u00famero 50.", None))
        self.btnNext_2.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_5.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES BINARIOS\n"
"DE BUSQUEDA", None))
        self.label_6.setText("")
        self.label_7.setText("")
        self.label_8.setText(QCoreApplication.translate("StackedWidget", u"50", None))
        self.label_9.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES BINARIOS\n"
"DE BUSQUEDA", None))
        self.label_10.setText(QCoreApplication.translate("StackedWidget", u"Las Ramas Gemelas (los Hijos Izquierdo y Derecho): \n"
"Desde cada \"nudo\" o punto donde hay un libro en el \u00e1rbol, siempre \n"
"salen dos ramas nuevas (como si fueran ramas gemelas):", None))
        self.btnNext_3.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_11.setText(QCoreApplication.translate("StackedWidget", u"Una rama se extiende \n"
"hacia la izquierda.\n"
" Por esta rama crecen \n"
"los libros con n\u00fameros m\u00e1s \n"
"peque\u00f1os que el libro en \n"
"el nudo actual.", None))
        self.label_12.setText(QCoreApplication.translate("StackedWidget", u"La otra rama se \n"
"extiende hacia la \n"
"derecha. Por esta rama \n"
"crecen los libros con \n"
"n\u00fameros m\u00e1s grandes \n"
"que el libro en \n"
"el nudo actual.", None))
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_15.setText(QCoreApplication.translate("StackedWidget", u"50", None))
        self.label_16.setText("")
        self.label_17.setText(QCoreApplication.translate("StackedWidget", u"30", None))
        self.label_18.setText(QCoreApplication.translate("StackedWidget", u"60", None))
        self.label_19.setText("")
        self.btnNext_4.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_20.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES BINARIOS\n"
"DE BUSQUEDA", None))
        self.label_21.setText(QCoreApplication.translate("StackedWidget", u"Ahora, tu \u00e1rbol va a darte otro libro, digamos que es el 20. \n"
"Para hacer esto, el \u00e1rbol se pregunta \u00bfEl 20 es mas grande o peque\u00f1o que el 50?\n"
"Como es mas peque\u00f1o, nos vamos a la rama izquierda y se vuelve a preguntar:\n"
" \u00bfEl 20 es mas grande o peque\u00f1o que el 30? Mas peque\u00f1o, entonces crecera una nueva \n"
"rama a la izquierda del 30 y ahi saldra el 20.", None))
        self.label_22.setText("")
        self.label_23.setText(QCoreApplication.translate("StackedWidget", u"50", None))
        self.label_24.setText("")
        self.label_25.setText(QCoreApplication.translate("StackedWidget", u"60", None))
        self.label_26.setText(QCoreApplication.translate("StackedWidget", u"30", None))
        self.label_27.setText("")
        self.label_28.setText("")
        self.label_29.setText("")
        self.label_30.setText("")
        self.label_31.setText(QCoreApplication.translate("StackedWidget", u"20", None))
        self.label_32.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES BINARIOS\n"
"DE BUSQUEDA", None))
        self.btnNext_5.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_33.setText(QCoreApplication.translate("StackedWidget", u"Ahora para buscar en este arbolito alg\u00fan libro que queramos, debemos\n"
" hacernos las mismas preguntas que el \u00e1rbol se hacia.\n"
"Digamos que queremos buscar el que acaba que crecer, el 20.\n"
" \u00bfEl 20 es m\u00e1s grande o peque\u00f1o que el 50?", None))
        self.label_34.setText(QCoreApplication.translate("StackedWidget", u"\u00bfEl 20 es mas grande\n"
" o pque\u00f1o que el 30?", None))
        self.label_35.setText("")
        self.label_36.setText(QCoreApplication.translate("StackedWidget", u"20", None))
        self.label_37.setText(QCoreApplication.translate("StackedWidget", u"60", None))
        self.label_38.setText("")
        self.label_39.setText(QCoreApplication.translate("StackedWidget", u"50", None))
        self.label_40.setText("")
        self.label_41.setText("")
        self.label_42.setText("")
        self.label_43.setText("")
        self.label_44.setText(QCoreApplication.translate("StackedWidget", u"30", None))
        self.label_45.setText(QCoreApplication.translate("StackedWidget", u"Y LISTO, LLEGAMOS\n"
"A DONDE ESTA\n"
" EL N\u00daMERO 20", None))
        self.label_46.setText(QCoreApplication.translate("StackedWidget", u"Mas peque\u00f1o\n"
"nos movemos a la \n"
"rama izquierda", None))
        self.label_47.setText(QCoreApplication.translate("StackedWidget", u"Mas peque\u00f1o\n"
" Nos movemos a la izquierda", None))
        self.btnNext_6.setText(QCoreApplication.translate("StackedWidget", u"TERMINADO", None))
        self.label_48.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES BINARIOS\n"
"DE BUSQUEDA", None))
        self.label_49.setText(QCoreApplication.translate("StackedWidget", u"Asi es como funciona un \u00e1rbol binario de \n"
"busqueda, te gust\u00f3 el procedimiento?\n"
"\u00bfSe te hizo dificil?\n"
"\u00bfQu\u00e9 te pareci\u00f3?", None))
        self.label_50.setText("")
        self.label_51.setText("")
    # retranslateUi

