# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'arbolesAutoBalanceados.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        if not StackedWidget.objectName():
            StackedWidget.setObjectName(u"StackedWidget")
        StackedWidget.resize(761, 521)
        StackedWidget.setStyleSheet(u"background-color:rgb(121, 27, 116)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 20, 651, 91))
        font = QFont()
        font.setFamilies([u"Caprasimo"])
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 140, 701, 81))
        font1 = QFont()
        font1.setFamilies([u"Caprasimo"])
        font1.setPointSize(12)
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext = QPushButton(self.page)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(670, 480, 75, 24))
        self.btnNext.setStyleSheet(u"background-color:rgb(69, 6, 74)")
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(270, 350, 131, 101))
        self.label_3.setPixmap(QPixmap(u"Sources/Images/ramas.png"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(360, 270, 131, 101))
        self.label_4.setPixmap(QPixmap(u"Sources/Images/ramas.png"))
        self.label_4.setScaledContents(True)
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(440, 250, 71, 61))
        self.label_6.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.page)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(340, 330, 71, 61))
        self.label_7.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(self.page)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(240, 410, 71, 61))
        self.label_8.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_8.setScaledContents(True)
        self.label_9 = QLabel(self.page)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(460, 260, 31, 21))
        self.label_9.setFont(font1)
        self.label_9.setStyleSheet(u"background-color:white;color:black")
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_10 = QLabel(self.page)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(360, 340, 31, 21))
        self.label_10.setFont(font1)
        self.label_10.setStyleSheet(u"background-color:white;color:black")
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_11 = QLabel(self.page)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(260, 420, 31, 21))
        self.label_11.setFont(font1)
        self.label_11.setStyleSheet(u"background-color:white;color:black")
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_12 = QLabel(self.page_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(50, 20, 651, 91))
        self.label_12.setFont(font)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_2 = QPushButton(self.page_2)
        self.btnNext_2.setObjectName(u"btnNext_2")
        self.btnNext_2.setGeometry(QRect(670, 480, 75, 24))
        self.btnNext_2.setStyleSheet(u"background-color:rgb(69, 6, 74)")
        self.label_13 = QLabel(self.page_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 140, 701, 41))
        self.label_13.setFont(font1)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_14 = QLabel(self.page_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(30, 210, 691, 111))
        self.label_14.setFont(font1)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_15 = QLabel(self.page_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(150, 340, 461, 131))
        self.label_15.setPixmap(QPixmap(u"Sources/Images/magia.png"))
        self.label_15.setScaledContents(True)
        StackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(50, 20, 651, 91))
        self.label_16.setFont(font)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_3 = QPushButton(self.page_3)
        self.btnNext_3.setObjectName(u"btnNext_3")
        self.btnNext_3.setGeometry(QRect(670, 480, 75, 24))
        self.btnNext_3.setStyleSheet(u"background-color:rgb(69, 6, 74)")
        self.label_17 = QLabel(self.page_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 130, 701, 111))
        self.label_17.setFont(font1)
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_18 = QLabel(self.page_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(100, 365, 111, 101))
        self.label_18.setPixmap(QPixmap(u"Sources/Images/ramas.png"))
        self.label_18.setScaledContents(True)
        self.label_19 = QLabel(self.page_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(190, 270, 111, 101))
        self.label_19.setPixmap(QPixmap(u"Sources/Images/ramas.png"))
        self.label_19.setScaledContents(True)
        self.label_20 = QLabel(self.page_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(160, 330, 71, 61))
        self.label_20.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_20.setScaledContents(True)
        self.label_21 = QLabel(self.page_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(80, 430, 71, 61))
        self.label_21.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_21.setScaledContents(True)
        self.label_22 = QLabel(self.page_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(270, 260, 31, 21))
        self.label_22.setFont(font1)
        self.label_22.setStyleSheet(u"background-color:white;color:black")
        self.label_22.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_23 = QLabel(self.page_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(250, 250, 71, 61))
        self.label_23.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_23.setScaledContents(True)
        self.label_24 = QLabel(self.page_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(180, 340, 31, 21))
        self.label_24.setFont(font1)
        self.label_24.setStyleSheet(u"background-color:white;color:black")
        self.label_24.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_25 = QLabel(self.page_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(100, 440, 31, 21))
        self.label_25.setFont(font1)
        self.label_25.setStyleSheet(u"background-color:white;color:black")
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(self.page_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(340, 360, 31, 31))
        font2 = QFont()
        font2.setFamilies([u"Caprasimo"])
        font2.setPointSize(26)
        self.label_5.setFont(font2)
        self.label_26 = QLabel(self.page_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(550, 330, 111, 101))
        self.label_26.setPixmap(QPixmap(u"Sources/Images/amar.png"))
        self.label_26.setScaledContents(True)
        self.label_27 = QLabel(self.page_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(430, 330, 111, 101))
        self.label_27.setPixmap(QPixmap(u"Sources/Images/ramas.png"))
        self.label_27.setScaledContents(True)
        self.label_28 = QLabel(self.page_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(630, 400, 31, 21))
        self.label_28.setFont(font1)
        self.label_28.setStyleSheet(u"background-color:white;color:black")
        self.label_28.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_29 = QLabel(self.page_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(610, 390, 71, 61))
        self.label_29.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_29.setScaledContents(True)
        self.label_30 = QLabel(self.page_3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(420, 400, 31, 21))
        self.label_30.setFont(font1)
        self.label_30.setStyleSheet(u"background-color:white;color:black")
        self.label_30.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_31 = QLabel(self.page_3)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(400, 390, 71, 61))
        self.label_31.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_31.setScaledContents(True)
        self.label_32 = QLabel(self.page_3)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(500, 310, 71, 61))
        self.label_32.setPixmap(QPixmap(u"Sources/Images/libros.png"))
        self.label_32.setScaledContents(True)
        self.label_33 = QLabel(self.page_3)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(520, 320, 31, 21))
        self.label_33.setFont(font1)
        self.label_33.setStyleSheet(u"background-color:white;color:black")
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StackedWidget.addWidget(self.page_3)
        self.label_16.raise_()
        self.btnNext_3.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_22.raise_()
        self.label_5.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_29.raise_()
        self.label_28.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_30.raise_()
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.btnNext_4 = QPushButton(self.page_4)
        self.btnNext_4.setObjectName(u"btnNext_4")
        self.btnNext_4.setGeometry(QRect(670, 480, 75, 24))
        self.btnNext_4.setStyleSheet(u"background-color:rgb(69, 6, 74)")
        self.label_34 = QLabel(self.page_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(50, 20, 651, 91))
        self.label_34.setFont(font)
        self.label_34.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_35 = QLabel(self.page_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(40, 130, 701, 111))
        self.label_35.setFont(font1)
        self.label_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_36 = QLabel(self.page_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(30, 230, 711, 91))
        self.label_36.setFont(font1)
        self.label_36.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_37 = QLabel(self.page_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(170, 340, 131, 141))
        self.label_37.setPixmap(QPixmap(u"Sources/Images/duende.png"))
        self.label_37.setScaledContents(True)
        self.label_38 = QLabel(self.page_4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(500, 340, 121, 141))
        self.label_38.setPixmap(QPixmap(u"Sources/Images/duende.png"))
        self.label_38.setScaledContents(True)
        StackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.btnTerminar = QPushButton(self.page_5)
        self.btnTerminar.setObjectName(u"btnTerminar")
        self.btnTerminar.setGeometry(QRect(270, 370, 231, 81))
        font3 = QFont()
        font3.setFamilies([u"Caprasimo"])
        font3.setPointSize(22)
        self.btnTerminar.setFont(font3)
        self.btnTerminar.setStyleSheet(u"background-color:rgb(69, 6, 74)")
        self.label_39 = QLabel(self.page_5)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(50, 20, 651, 91))
        self.label_39.setFont(font)
        self.label_39.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_40 = QLabel(self.page_5)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(40, 120, 691, 141))
        self.label_40.setFont(font1)
        self.label_40.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_41 = QLabel(self.page_5)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(160, 260, 431, 91))
        self.label_41.setPixmap(QPixmap(u"Sources/Images/magia.png"))
        self.label_41.setScaledContents(True)
        StackedWidget.addWidget(self.page_5)

        self.retranslateUi(StackedWidget)

        StackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(StackedWidget)
    # setupUi

    def retranslateUi(self, StackedWidget):
        StackedWidget.setWindowTitle(QCoreApplication.translate("StackedWidget", u"StackedWidget", None))
        self.label.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES \n"
"AUTOBALANCEADOS", None))
        self.label_2.setText(QCoreApplication.translate("StackedWidget", u"Imagina nuestro \u00e1rbol de libros m\u00e1gicos. A veces, si solo pones libros m\u00e1s peque\u00f1os \n"
"a la izquierda, y luego m\u00e1s libros peque\u00f1os a la izquierda de esos, y as\u00ed sucesivamente,\n"
" tu \u00e1rbol puede crecer muy, muy alto y delgado por un solo lado, \n"
"\u00a1como un \u00e1rbol que se est\u00e1 cayendo de lado!", None))
        self.btnNext.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_6.setText("")
        self.label_7.setText("")
        self.label_8.setText("")
        self.label_9.setText(QCoreApplication.translate("StackedWidget", u"50", None))
        self.label_10.setText(QCoreApplication.translate("StackedWidget", u"40", None))
        self.label_11.setText(QCoreApplication.translate("StackedWidget", u"30", None))
        self.label_12.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES \n"
"AUTOBALANCEADOS", None))
        self.btnNext_2.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_13.setText(QCoreApplication.translate("StackedWidget", u"Cuando un \u00e1rbol crece as\u00ed de desequilibrado, encontrar un libro se vuelve \n"
"un poco m\u00e1s lento, \u00a1porque tienes que bajar por una rama muy larga!", None))
        self.label_14.setText(QCoreApplication.translate("StackedWidget", u"Un \u00e1rbol m\u00e1gico autobalanceado es un \u00e1rbol muy inteligente \n"
"que, cada vez que le pones un libro nuevo o le quitas uno, se reorganiza solito para \n"
"que todas sus ramas est\u00e9n m\u00e1s o menos del mismo largo. Es como si el \u00e1rbol \n"
"tuviera una peque\u00f1a magia que lo mantiene siempre\n"
" bonito y \"en forma\", sin importar cu\u00e1ntos libros le pongas o de qu\u00e9 tama\u00f1o sean.", None))
        self.label_15.setText("")
        self.label_16.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES \n"
"AUTOBALANCEADOS", None))
        self.btnNext_3.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_17.setText(QCoreApplication.translate("StackedWidget", u"Rotaciones M\u00e1gicas: Cuando el \u00e1rbol nota que una rama se est\u00e1 haciendo demasiado \n"
"larga y que podr\u00eda desequilibrar todo, los duendes hacen unas \"rotaciones\". Imagina \n"
"que toman algunos libros y los giran un poco para que cambien de lugar con otros \n"
"libros cercanos. Esto hace que las ramas se acorten y el \u00e1rbol vuelva a estar m\u00e1s parejo. \n"
"No cambian los n\u00fameros de los libros, \u00a1solo su posici\u00f3n en el \u00e1rbol!", None))
        self.label_18.setText("")
        self.label_19.setText("")
        self.label_20.setText("")
        self.label_21.setText("")
        self.label_22.setText(QCoreApplication.translate("StackedWidget", u"50", None))
        self.label_23.setText("")
        self.label_24.setText(QCoreApplication.translate("StackedWidget", u"40", None))
        self.label_25.setText(QCoreApplication.translate("StackedWidget", u"30", None))
        self.label_5.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_26.setText("")
        self.label_27.setText("")
        self.label_28.setText(QCoreApplication.translate("StackedWidget", u"50", None))
        self.label_29.setText("")
        self.label_30.setText(QCoreApplication.translate("StackedWidget", u"30", None))
        self.label_31.setText("")
        self.label_32.setText("")
        self.label_33.setText(QCoreApplication.translate("StackedWidget", u"40", None))
        self.btnNext_4.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_34.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES \n"
"AUTOBALANCEADOS", None))
        self.label_35.setText(QCoreApplication.translate("StackedWidget", u"Asi como hay rotaciones a la izquierda, hay hacia la derecha, \n"
"asi que cada vez que crezca un libro o se quite un libro,los duendes \n"
" har\u00e1n su magia para acomodar el \u00e1rbol otra vez y dejarlo bonito. ", None))
        self.label_36.setText(QCoreApplication.translate("StackedWidget", u"El objetivo de la magia es que la distancia desde el tronco principal \n"
"hasta cualquier libro que est\u00e9 en la parte m\u00e1s baja del \u00e1rbol \n"
"(en las \"hojas\" del \u00e1rbol) sea casi la misma para todos. \n"
"As\u00ed, no importa qu\u00e9 libro busques, el camino siempre ser\u00e1 corto y r\u00e1pido.", None))
        self.label_37.setText("")
        self.label_38.setText("")
        self.btnTerminar.setText(QCoreApplication.translate("StackedWidget", u"TERMINADO", None))
        self.label_39.setText(QCoreApplication.translate("StackedWidget", u"ARBOLES \n"
"AUTOBALANCEADOS", None))
        self.label_40.setText(QCoreApplication.translate("StackedWidget", u"En resumen, un \u00e1rbol m\u00e1gico autobalanceado es como nuestro \n"
"\u00e1rbol de libros, pero con una magia extra que lo mantiene siempre bonito y ordenado\n"
", asegurando que buscar cualquier libro sea siempre igual de r\u00e1pido \n"
"y eficiente. \u00a1Es un s\u00faper organizador de libros que se cuida solito!", None))
        self.label_41.setText("")
    # retranslateUi

