# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CountingSort.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        if not StackedWidget.objectName():
            StackedWidget.setObjectName(u"StackedWidget")
        StackedWidget.resize(761, 521)
        StackedWidget.setStyleSheet(u"background-color:rgb(115, 80, 156)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(180, 20, 401, 61))
        font = QFont()
        font.setFamilies([u"Caprasimo"])
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(100, 90, 551, 91))
        font1 = QFont()
        font1.setFamilies([u"Caprasimo"])
        font1.setPointSize(12)
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext = QPushButton(self.page)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(660, 480, 75, 24))
        self.btnNext.setStyleSheet(u"background-color:rgb(71, 18, 124)")
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(140, 230, 201, 221))
        self.label_3.setPixmap(QPixmap(u"Sources/Images/frasco.png"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(390, 220, 251, 241))
        self.label_4.setPixmap(QPixmap(u"Sources/Images/hoja.png"))
        self.label_4.setScaledContents(True)
        StackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(180, 20, 401, 61))
        self.label_5.setFont(font)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_2 = QPushButton(self.page_2)
        self.btnNext_2.setObjectName(u"btnNext_2")
        self.btnNext_2.setGeometry(QRect(670, 480, 75, 24))
        self.btnNext_2.setStyleSheet(u"background-color:rgb(71, 18, 124)")
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 90, 551, 181))
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(90, 300, 141, 161))
        self.label_7.setPixmap(QPixmap(u"Sources/Images/frasco.png"))
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(240, 360, 31, 31))
        font2 = QFont()
        font2.setFamilies([u"Caprasimo"])
        font2.setPointSize(28)
        self.label_8.setFont(font2)
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(480, 290, 191, 181))
        self.label_9.setPixmap(QPixmap(u"Sources/Images/hoja.png"))
        self.label_9.setScaledContents(True)
        self.label_10 = QLabel(self.page_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(290, 290, 81, 81))
        self.label_10.setPixmap(QPixmap(u"Sources/Images/canica roja.png"))
        self.label_10.setScaledContents(True)
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(310, 370, 81, 81))
        self.label_11.setPixmap(QPixmap(u"Sources/Images/canica roja.png"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.page_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(370, 300, 81, 81))
        self.label_12.setPixmap(QPixmap(u"Sources/Images/canica roja.png"))
        self.label_12.setScaledContents(True)
        self.label_13 = QLabel(self.page_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(450, 360, 31, 31))
        self.label_13.setFont(font2)
        self.label_14 = QLabel(self.page_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(540, 320, 41, 41))
        font3 = QFont()
        font3.setPointSize(12)
        self.label_14.setFont(font3)
        self.label_14.setStyleSheet(u"background-color:transparent;\n"
"color: black\n"
"")
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_15 = QLabel(self.page_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(100, 80, 551, 151))
        self.label_15.setFont(font1)
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(180, 20, 401, 61))
        self.label_16.setFont(font)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_3 = QPushButton(self.page_3)
        self.btnNext_3.setObjectName(u"btnNext_3")
        self.btnNext_3.setGeometry(QRect(670, 480, 75, 24))
        self.btnNext_3.setStyleSheet(u"background-color:rgb(71, 18, 124)")
        self.label_17 = QLabel(self.page_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(180, 300, 141, 151))
        self.label_17.setPixmap(QPixmap(u"Sources/Images/vacio.png"))
        self.label_17.setScaledContents(True)
        self.label_18 = QLabel(self.page_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(340, 350, 31, 31))
        self.label_18.setFont(font2)
        self.label_19 = QLabel(self.page_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(440, 310, 41, 41))
        self.label_19.setFont(font3)
        self.label_19.setStyleSheet(u"background-color:transparent;\n"
"color: black\n"
"")
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_20 = QLabel(self.page_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(370, 250, 251, 221))
        self.label_20.setPixmap(QPixmap(u"Sources/Images/hoja.png"))
        self.label_20.setScaledContents(True)
        self.label_21 = QLabel(self.page_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(500, 300, 41, 41))
        self.label_21.setFont(font3)
        self.label_21.setStyleSheet(u"background-color:transparent;\n"
"color: black\n"
"")
        self.label_21.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_22 = QLabel(self.page_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(450, 380, 41, 41))
        self.label_22.setFont(font3)
        self.label_22.setStyleSheet(u"background-color:transparent;\n"
"color: black\n"
"")
        self.label_22.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_23 = QLabel(self.page_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(490, 360, 71, 31))
        self.label_23.setFont(font3)
        self.label_23.setStyleSheet(u"background-color:transparent;\n"
"color: black\n"
"")
        self.label_23.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StackedWidget.addWidget(self.page_3)
        self.label_15.raise_()
        self.label_16.raise_()
        self.btnNext_3.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_20.raise_()
        self.label_19.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_24 = QLabel(self.page_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(180, 20, 401, 61))
        self.label_24.setFont(font)
        self.label_24.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_25 = QLabel(self.page_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(100, 80, 551, 151))
        self.label_25.setFont(font1)
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_4 = QPushButton(self.page_4)
        self.btnNext_4.setObjectName(u"btnNext_4")
        self.btnNext_4.setGeometry(QRect(670, 480, 75, 24))
        self.btnNext_4.setStyleSheet(u"background-color:rgb(71, 18, 124)")
        self.label_26 = QLabel(self.page_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(90, 320, 41, 41))
        self.label_26.setFont(font3)
        self.label_26.setStyleSheet(u"background-color:transparent;\n"
"color: black\n"
"")
        self.label_26.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_27 = QLabel(self.page_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(270, 350, 31, 31))
        self.label_27.setFont(font2)
        self.label_28 = QLabel(self.page_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(140, 370, 71, 31))
        self.label_28.setFont(font3)
        self.label_28.setStyleSheet(u"background-color:transparent;\n"
"color: black\n"
"")
        self.label_28.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_29 = QLabel(self.page_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(100, 390, 41, 41))
        self.label_29.setFont(font3)
        self.label_29.setStyleSheet(u"background-color:transparent;\n"
"color: black\n"
"")
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_30 = QLabel(self.page_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(150, 310, 41, 41))
        self.label_30.setFont(font3)
        self.label_30.setStyleSheet(u"background-color:transparent;\n"
"color: black\n"
"")
        self.label_30.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_31 = QLabel(self.page_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(20, 260, 251, 221))
        self.label_31.setPixmap(QPixmap(u"Sources/Images/hoja.png"))
        self.label_31.setScaledContents(True)
        self.label_32 = QLabel(self.page_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(310, 260, 81, 81))
        self.label_32.setPixmap(QPixmap(u"Sources/Images/canica roja.png"))
        self.label_32.setScaledContents(True)
        self.label_33 = QLabel(self.page_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(390, 260, 81, 81))
        self.label_33.setPixmap(QPixmap(u"Sources/Images/canica roja.png"))
        self.label_33.setScaledContents(True)
        self.label_34 = QLabel(self.page_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(470, 260, 81, 81))
        self.label_34.setPixmap(QPixmap(u"Sources/Images/canica roja.png"))
        self.label_34.setScaledContents(True)
        self.label_35 = QLabel(self.page_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(550, 260, 91, 81))
        self.label_35.setPixmap(QPixmap(u"Sources/Images/canica azul.png"))
        self.label_35.setScaledContents(True)
        self.label_36 = QLabel(self.page_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(630, 260, 91, 81))
        self.label_36.setPixmap(QPixmap(u"Sources/Images/canica azul.png"))
        self.label_36.setScaledContents(True)
        self.label_37 = QLabel(self.page_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(310, 350, 71, 71))
        self.label_37.setPixmap(QPixmap(u"Sources/Images/canica verde.png"))
        self.label_37.setScaledContents(True)
        self.label_38 = QLabel(self.page_4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(390, 350, 61, 61))
        self.label_38.setPixmap(QPixmap(u"Sources/Images/canica amarilla.png"))
        self.label_38.setScaledContents(True)
        self.label_39 = QLabel(self.page_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(450, 350, 61, 61))
        self.label_39.setPixmap(QPixmap(u"Sources/Images/canica amarilla.png"))
        self.label_39.setScaledContents(True)
        self.label_40 = QLabel(self.page_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(510, 350, 61, 61))
        self.label_40.setPixmap(QPixmap(u"Sources/Images/canica amarilla.png"))
        self.label_40.setScaledContents(True)
        self.label_41 = QLabel(self.page_4)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(570, 350, 61, 61))
        self.label_41.setPixmap(QPixmap(u"Sources/Images/canica amarilla.png"))
        self.label_41.setScaledContents(True)
        self.label_42 = QLabel(self.page_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(640, 350, 61, 61))
        self.label_42.setPixmap(QPixmap(u"Sources/Images/canica amarilla.png"))
        self.label_42.setScaledContents(True)
        StackedWidget.addWidget(self.page_4)
        self.label_24.raise_()
        self.label_25.raise_()
        self.btnNext_4.raise_()
        self.label_27.raise_()
        self.label_31.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_26.raise_()
        self.label_28.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.btnTerminado = QPushButton(self.page_5)
        self.btnTerminado.setObjectName(u"btnTerminado")
        self.btnTerminado.setGeometry(QRect(290, 410, 171, 71))
        font4 = QFont()
        font4.setFamilies([u"Caprasimo"])
        font4.setPointSize(11)
        self.btnTerminado.setFont(font4)
        self.btnTerminado.setStyleSheet(u"background-color:rgb(71, 18, 124)")
        self.label_43 = QLabel(self.page_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(180, 20, 401, 61))
        self.label_43.setFont(font)
        self.label_43.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_44 = QLabel(self.page_5)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(100, 80, 551, 151))
        self.label_44.setFont(font1)
        self.label_44.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_45 = QLabel(self.page_5)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(280, 230, 81, 81))
        self.label_45.setPixmap(QPixmap(u"Sources/Images/canica roja.png"))
        self.label_45.setScaledContents(True)
        self.label_46 = QLabel(self.page_5)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(340, 320, 61, 61))
        self.label_46.setPixmap(QPixmap(u"Sources/Images/canica amarilla.png"))
        self.label_46.setScaledContents(True)
        self.label_47 = QLabel(self.page_5)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(530, 240, 71, 71))
        self.label_47.setPixmap(QPixmap(u"Sources/Images/canica verde.png"))
        self.label_47.setScaledContents(True)
        self.label_48 = QLabel(self.page_5)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(280, 320, 61, 61))
        self.label_48.setPixmap(QPixmap(u"Sources/Images/canica amarilla.png"))
        self.label_48.setScaledContents(True)
        self.label_49 = QLabel(self.page_5)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(140, 230, 81, 81))
        self.label_49.setPixmap(QPixmap(u"Sources/Images/canica roja.png"))
        self.label_49.setScaledContents(True)
        self.label_50 = QLabel(self.page_5)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(400, 320, 61, 61))
        self.label_50.setPixmap(QPixmap(u"Sources/Images/canica amarilla.png"))
        self.label_50.setScaledContents(True)
        self.label_51 = QLabel(self.page_5)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(220, 320, 61, 61))
        self.label_51.setPixmap(QPixmap(u"Sources/Images/canica amarilla.png"))
        self.label_51.setScaledContents(True)
        self.label_52 = QLabel(self.page_5)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(350, 240, 91, 81))
        self.label_52.setPixmap(QPixmap(u"Sources/Images/canica azul.png"))
        self.label_52.setScaledContents(True)
        self.label_53 = QLabel(self.page_5)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(470, 320, 61, 61))
        self.label_53.setPixmap(QPixmap(u"Sources/Images/canica amarilla.png"))
        self.label_53.setScaledContents(True)
        self.label_55 = QLabel(self.page_5)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(440, 240, 91, 81))
        self.label_55.setPixmap(QPixmap(u"Sources/Images/canica azul.png"))
        self.label_55.setScaledContents(True)
        self.label_56 = QLabel(self.page_5)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(210, 230, 81, 81))
        self.label_56.setPixmap(QPixmap(u"Sources/Images/canica roja.png"))
        self.label_56.setScaledContents(True)
        StackedWidget.addWidget(self.page_5)

        self.retranslateUi(StackedWidget)

        StackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(StackedWidget)
    # setupUi

    def retranslateUi(self, StackedWidget):
        StackedWidget.setWindowTitle(QCoreApplication.translate("StackedWidget", u"StackedWidget", None))
        self.label.setText(QCoreApplication.translate("StackedWidget", u"COUNTING SORT", None))
        self.label_2.setText(QCoreApplication.translate("StackedWidget", u"Imagina que tienes un gran frasco lleno de canicas de diferentes \n"
"colores: rojas, azules, verdes y amarillas. Y quieres ordenarlas \n"
"para saber exactamente cu\u00e1ntas canicas hay de cada color, y luego \n"
"ponerlas todas en una fila por color.\n"
" Vamos a necesitar una hoja de papel.", None))
        self.btnNext.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText(QCoreApplication.translate("StackedWidget", u"COUNTING SORT", None))
        self.btnNext_2.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_6.setText(QCoreApplication.translate("StackedWidget", u"As\u00ed es como Counting Sort te ayudar\u00eda:\n"
"\u00a1Contemos los colores! \n"
"Vas a tomar tu hoja de papel.\n"
"En esta hoja, vas a escribir el nombre de cada \n"
"color de canica que tienes: \n"
"\"Rojo\", \"Azul\", \"Verde\", \"Amarillo\".\n"
"Ahora, vas a ir sacando las canicas del fraco una por una.\n"
"Cada vez que saques una canica, vas a hacer \n"
"una marca al lado de su color en tu hoja.", None))
        self.label_7.setText("")
        self.label_8.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_9.setText("")
        self.label_10.setText("")
        self.label_11.setText("")
        self.label_12.setText("")
        self.label_13.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_14.setText(QCoreApplication.translate("StackedWidget", u"Rojas\n"
" III", None))
        self.label_15.setText(QCoreApplication.translate("StackedWidget", u"Sacas una roja: pones una marca al lado de \"Rojo\".\n"
"Sacas una verde: pones una marca al lado de \"Verde\".\n"
"Y as\u00ed hasta que la cesta est\u00e9 vac\u00eda.\n"
"Al final, en tu tabla, podr\u00e1s ver r\u00e1pidamente \n"
"cu\u00e1ntas marcas tienes para cada color. \n"
"\u00a1Sabes cu\u00e1ntas canicas rojas tienes, cu\u00e1ntas azules, etc.!", None))
        self.label_16.setText(QCoreApplication.translate("StackedWidget", u"COUNTING SORT", None))
        self.btnNext_3.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_17.setText("")
        self.label_18.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_19.setText(QCoreApplication.translate("StackedWidget", u"Rojas\n"
" III", None))
        self.label_20.setText("")
        self.label_21.setText(QCoreApplication.translate("StackedWidget", u"Azul\n"
" II", None))
        self.label_22.setText(QCoreApplication.translate("StackedWidget", u"Verde\n"
" I", None))
        self.label_23.setText(QCoreApplication.translate("StackedWidget", u"Amarillo\n"
" IIIII", None))
        self.label_24.setText(QCoreApplication.translate("StackedWidget", u"COUNTING SORT", None))
        self.label_25.setText(QCoreApplication.translate("StackedWidget", u"\u00a1Hora de ponerlas en fila! \n"
"Ahora que sabes cu\u00e1ntas canicas hay de cada color, \n"
"vas a empezar a ponerlas en una fila muy ordenada.\n"
"Primero, pones todas las canicas rojas que contaste en la fila.\n"
"Luego, despu\u00e9s de las rojas, pones todas las canicas azules \n"
"Despu\u00e9s las verdes, y finalmente las amarillas.", None))
        self.btnNext_4.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_26.setText(QCoreApplication.translate("StackedWidget", u"Rojas\n"
" III", None))
        self.label_27.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_28.setText(QCoreApplication.translate("StackedWidget", u"Amarillo\n"
" IIIII", None))
        self.label_29.setText(QCoreApplication.translate("StackedWidget", u"Verde\n"
" I", None))
        self.label_30.setText(QCoreApplication.translate("StackedWidget", u"Azul\n"
" II", None))
        self.label_31.setText("")
        self.label_32.setText("")
        self.label_33.setText("")
        self.label_34.setText("")
        self.label_35.setText("")
        self.label_36.setText("")
        self.label_37.setText("")
        self.label_38.setText("")
        self.label_39.setText("")
        self.label_40.setText("")
        self.label_41.setText("")
        self.label_42.setText("")
        self.btnTerminado.setText(QCoreApplication.translate("StackedWidget", u"TERMINADO", None))
        self.label_43.setText(QCoreApplication.translate("StackedWidget", u"COUNTING SORT", None))
        self.label_44.setText(QCoreApplication.translate("StackedWidget", u"\u00a1Y listo! Tienes una fila perfectamente ordenada de canicas,\n"
" primero todas las rojas, luego todas las azules, y as\u00ed sucesivamente.", None))
        self.label_45.setText("")
        self.label_46.setText("")
        self.label_47.setText("")
        self.label_48.setText("")
        self.label_49.setText("")
        self.label_50.setText("")
        self.label_51.setText("")
        self.label_52.setText("")
        self.label_53.setText("")
        self.label_55.setText("")
        self.label_56.setText("")
    # retranslateUi

