# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Dijkstra.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_dijkstraVista(object):
    def setupUi(self, dijkstraVista):
        if not dijkstraVista.objectName():
            dijkstraVista.setObjectName(u"dijkstraVista")
        dijkstraVista.resize(827, 490)
        dijkstraVista.setStyleSheet(u"background-color: rgb(125, 255, 187)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(260, 10, 261, 31))
        self.label.setStyleSheet(u"color: black; font: bold; font-size: 18pt")
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(140, 50, 551, 71))
        self.label_2.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(120, 380, 551, 71))
        self.label_4.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_4.setWordWrap(True)
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 110, 701, 261))
        self.label_3.setPixmap(QPixmap(u"Sources/Images/grafo.jpg.png"))
        self.label_3.setScaledContents(True)
        self.btnNext = QPushButton(self.page)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(700, 440, 75, 24))
        self.btnNext.setStyleSheet(u"; background-color: black")
        dijkstraVista.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(60, 130, 701, 261))
        self.label_5.setPixmap(QPixmap(u"Sources/Images/grafo.jpg.png"))
        self.label_5.setScaledContents(True)
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(260, 10, 261, 31))
        self.label_6.setStyleSheet(u"color: black; font: bold; font-size: 18pt")
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(90, 370, 551, 71))
        self.label_7.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_7.setWordWrap(True)
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(140, 60, 551, 71))
        self.label_8.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_8.setWordWrap(True)
        self.btnNext_2 = QPushButton(self.page_2)
        self.btnNext_2.setObjectName(u"btnNext_2")
        self.btnNext_2.setGeometry(QRect(720, 430, 75, 24))
        self.btnNext_2.setStyleSheet(u"; background-color: black")
        dijkstraVista.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_9 = QLabel(self.page_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 370, 551, 71))
        self.label_9.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_9.setWordWrap(True)
        self.label_10 = QLabel(self.page_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(250, 10, 261, 31))
        self.label_10.setStyleSheet(u"color: black; font: bold; font-size: 18pt")
        self.label_11 = QLabel(self.page_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(50, 100, 731, 271))
        self.label_11.setPixmap(QPixmap(u"Sources/Images/grafo2.png"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.page_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(130, 50, 551, 71))
        self.label_12.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_12.setWordWrap(True)
        self.btnNext_3 = QPushButton(self.page_3)
        self.btnNext_3.setObjectName(u"btnNext_3")
        self.btnNext_3.setGeometry(QRect(720, 430, 75, 24))
        self.btnNext_3.setStyleSheet(u"; background-color: black")
        dijkstraVista.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_13 = QLabel(self.page_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(120, 370, 551, 71))
        self.label_13.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_13.setWordWrap(True)
        self.label_14 = QLabel(self.page_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(130, 40, 551, 71))
        self.label_14.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_14.setWordWrap(True)
        self.label_15 = QLabel(self.page_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(250, 10, 261, 31))
        self.label_15.setStyleSheet(u"color: black; font: bold; font-size: 18pt")
        self.label_16 = QLabel(self.page_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(60, 100, 731, 271))
        self.label_16.setPixmap(QPixmap(u"Sources/Images/grafo2.png"))
        self.label_16.setScaledContents(True)
        self.btnNext_4 = QPushButton(self.page_4)
        self.btnNext_4.setObjectName(u"btnNext_4")
        self.btnNext_4.setGeometry(QRect(720, 430, 75, 24))
        self.btnNext_4.setStyleSheet(u"; background-color: black")
        dijkstraVista.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.label_17 = QLabel(self.page_5)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(130, 360, 551, 71))
        self.label_17.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_17.setWordWrap(True)
        self.label_18 = QLabel(self.page_5)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(130, 40, 551, 71))
        self.label_18.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_18.setWordWrap(True)
        self.label_19 = QLabel(self.page_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(260, 10, 261, 31))
        self.label_19.setStyleSheet(u"color: black; font: bold; font-size: 18pt")
        self.label_20 = QLabel(self.page_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(50, 100, 731, 261))
        self.label_20.setPixmap(QPixmap(u"Sources/Images/grafo2.png"))
        self.label_20.setScaledContents(True)
        self.btnNext_5 = QPushButton(self.page_5)
        self.btnNext_5.setObjectName(u"btnNext_5")
        self.btnNext_5.setGeometry(QRect(730, 430, 75, 24))
        self.btnNext_5.setStyleSheet(u"; background-color: black")
        dijkstraVista.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.label_21 = QLabel(self.page_6)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(260, 10, 261, 31))
        self.label_21.setStyleSheet(u"color: black; font: bold; font-size: 18pt")
        self.label_22 = QLabel(self.page_6)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(100, 370, 661, 81))
        self.label_22.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_22.setWordWrap(True)
        self.label_23 = QLabel(self.page_6)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(60, 100, 731, 261))
        self.label_23.setPixmap(QPixmap(u"Sources/Images/grafo3.png"))
        self.label_23.setScaledContents(True)
        self.label_24 = QLabel(self.page_6)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(130, 50, 551, 51))
        self.label_24.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_24.setWordWrap(True)
        self.btnNext_6 = QPushButton(self.page_6)
        self.btnNext_6.setObjectName(u"btnNext_6")
        self.btnNext_6.setGeometry(QRect(730, 440, 75, 24))
        self.btnNext_6.setStyleSheet(u"; background-color: black")
        dijkstraVista.addWidget(self.page_6)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.label_25 = QLabel(self.page_7)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(240, 10, 261, 31))
        self.label_25.setStyleSheet(u"color: black; font: bold; font-size: 18pt")
        self.label_26 = QLabel(self.page_7)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(330, 40, 401, 71))
        self.label_26.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_26.setWordWrap(True)
        self.label_27 = QLabel(self.page_7)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(50, 100, 731, 261))
        self.label_27.setPixmap(QPixmap(u"Sources/Images/grafo4.png"))
        self.label_27.setScaledContents(True)
        self.label_28 = QLabel(self.page_7)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(110, 40, 221, 61))
        self.label_28.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_28.setWordWrap(True)
        self.label_29 = QLabel(self.page_7)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(120, 370, 611, 71))
        self.label_29.setStyleSheet(u"font-size: 12pt; color: black")
        self.label_29.setWordWrap(True)
        self.btnTerminar = QPushButton(self.page_7)
        self.btnTerminar.setObjectName(u"btnTerminar")
        self.btnTerminar.setGeometry(QRect(710, 440, 75, 24))
        self.btnTerminar.setStyleSheet(u"; background-color: black")
        dijkstraVista.addWidget(self.page_7)

        self.retranslateUi(dijkstraVista)

        dijkstraVista.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(dijkstraVista)
    # setupUi

    def retranslateUi(self, dijkstraVista):
        dijkstraVista.setWindowTitle(QCoreApplication.translate("dijkstraVista", u"StackedWidget", None))
        self.label.setText(QCoreApplication.translate("dijkstraVista", u"Busqueda por Dijkstra", None))
        self.label_2.setText(QCoreApplication.translate("dijkstraVista", u"Imagina que tienes el mapa de tu colonia como quisco algo asi", None))
        self.label_4.setText(QCoreApplication.translate("dijkstraVista", u"Para llegar lo mas rapido a la escuela, deberiamos de encontrar la ruta mas rapida para llegar", None))
        self.label_3.setText("")
        self.btnNext.setText(QCoreApplication.translate("dijkstraVista", u"Siguiente", None))
        self.label_5.setText("")
        self.label_6.setText(QCoreApplication.translate("dijkstraVista", u"Busqueda por Dijkstra", None))
        self.label_7.setText(QCoreApplication.translate("dijkstraVista", u"Ahora veremos los lugares mas cercanos o con menor tiempo de recorrido", None))
        self.label_8.setText(QCoreApplication.translate("dijkstraVista", u"Para empezar necesitamos anotar nuestros lugares visitados y nuestro lugar de comienzo, por eso marcamos como nuestra casa con un valor de 0", None))
        self.btnNext_2.setText(QCoreApplication.translate("dijkstraVista", u"Siguiente", None))
        self.label_9.setText(QCoreApplication.translate("dijkstraVista", u"Para actualizarlo sumaremos el valor de nuestra casa mas el tiempo de recorrido y veremos si es menor al valor que tienen los lugares, como es asi, el nuevo valor de los lugares es igual a la suma", None))
        self.label_10.setText(QCoreApplication.translate("dijkstraVista", u"Busqueda por Dijkstra", None))
        self.label_11.setText("")
        self.label_12.setText(QCoreApplication.translate("dijkstraVista", u"De nuestra casa tenemos la papeleria y el taller, entonces deberiamos actualizar nuestro mapa", None))
        self.btnNext_3.setText(QCoreApplication.translate("dijkstraVista", u"Siguiente", None))
        self.label_13.setText(QCoreApplication.translate("dijkstraVista", u"Para la papeleria podemos darnos cuenta que su flehca viene de la tienda de musica, entonces sabemos que por ahi no podemos pasar, cerramos esa ruta y la marcamos como visitada", None))
        self.label_14.setText(QCoreApplication.translate("dijkstraVista", u"Debemos elegir el camino con menos tiempo, en este caso ambas rutas tienen el mismo tiempo, entonces recorremos las dos", None))
        self.label_15.setText(QCoreApplication.translate("dijkstraVista", u"Busqueda por Dijkstra", None))
        self.label_16.setText("")
        self.btnNext_4.setText(QCoreApplication.translate("dijkstraVista", u"Siguiente", None))
        self.label_17.setText(QCoreApplication.translate("dijkstraVista", u"Del taller veremos cual es la ruta que sigue y nos damos cuente que hacia la heladeria, entonces repetimos el paso de antes para actualizar el mapa, sumamos el tiempo que llevamos, mas el que nos hariamos en llegar al taller", None))
        self.label_18.setText(QCoreApplication.translate("dijkstraVista", u"Si tomamos la ruta hacia el taller deberiamos hacer lo mismo, como este si tiene una ruta, aplicamos el mismo paso de antes", None))
        self.label_19.setText(QCoreApplication.translate("dijkstraVista", u"Busqueda por Dijkstra", None))
        self.label_20.setText("")
        self.btnNext_5.setText(QCoreApplication.translate("dijkstraVista", u"Siguiente", None))
        self.label_21.setText(QCoreApplication.translate("dijkstraVista", u"Busqueda por Dijkstra", None))
        self.label_22.setText(QCoreApplication.translate("dijkstraVista", u"Ahora, de la heladaria solo nos queda un lugar mas, la escuela, volvemos a repetir el mismo paso de antes para actualizar nuestro mapa, sumamos nuestros minutos actuales mas los 12 que nos hacemos para llegar a la escuela y si es menor que el numero que tiene la escuela, entonces actualizamos", None))
        self.label_23.setText("")
        self.label_24.setText(QCoreApplication.translate("dijkstraVista", u"Ahora el peso para pasar a la heladaria cambia a 8, que si se dan cuenta, es la suma de los minutos que llevamos recorridos", None))
        self.btnNext_6.setText(QCoreApplication.translate("dijkstraVista", u"Siguiente", None))
        self.label_25.setText(QCoreApplication.translate("dijkstraVista", u"Busqueda por Dijkstra", None))
        self.label_26.setText(QCoreApplication.translate("dijkstraVista", u"En total nos hicimos 20 minutos en llegar a la escuela desde nuestra casa con este mapa", None))
        self.label_27.setText("")
        self.label_28.setText(QCoreApplication.translate("dijkstraVista", u"Ya llegamos a la escuela!!!!", None))
        self.label_29.setText(QCoreApplication.translate("dijkstraVista", u"Si quisieramos hacer el camino de regreso de la escuela a nuestra casa, deberiamos de poner nuestro punto inicial la escuela y los tiempos de llegada de cada lugar en inifitno, justo como hicimos al principio", None))
        self.btnTerminar.setText(QCoreApplication.translate("dijkstraVista", u"Terminar", None))
    # retranslateUi

