# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GrafosProfundidad.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_VistaProfundiad(object):
    def setupUi(self, VistaProfundiad):
        if not VistaProfundiad.objectName():
            VistaProfundiad.setObjectName(u"VistaProfundiad")
        VistaProfundiad.resize(808, 566)
        VistaProfundiad.setStyleSheet(u"background-color: rgb(55,75,255)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 20, 351, 41))
        self.label.setStyleSheet(u"font-size: 18pt; font-weight: bold;")
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(90, 70, 541, 81))
        self.label_2.setStyleSheet(u"font-size:12pt;")
        self.label_2.setWordWrap(True)
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(180, 200, 131, 71))
        self.label_3.setPixmap(QPixmap(u"Sources/Images/motaniarusa.jpg"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(480, 230, 141, 91))
        self.label_4.setPixmap(QPixmap(u"Sources/Images/tesoro.jpg"))
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(400, 260, 131, 81))
        self.label_5.setPixmap(QPixmap(u"Sources/Images/trenecito.jpg"))
        self.label_5.setScaledContents(True)
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(250, 450, 131, 81))
        self.label_6.setPixmap(QPixmap(u"Sources/Images/entrada.jpg"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.page)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(60, 360, 111, 61))
        self.label_7.setPixmap(QPixmap(u"Sources/Images/chocones.jpg"))
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(self.page)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(550, 390, 131, 91))
        self.label_8.setPixmap(QPixmap(u"Sources/Images/ruleta.webp"))
        self.label_8.setScaledContents(True)
        self.btnNext = QPushButton(self.page)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(700, 520, 75, 24))
        self.btnNext.setStyleSheet(u"background-color:rgb(58,154,255)")
        self.label_9 = QLabel(self.page)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(390, 490, 71, 16))
        self.label_9.setStyleSheet(u"font-size: 12pt; font:bold;")
        VistaProfundiad.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_10 = QLabel(self.page_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(600, 210, 141, 91))
        self.label_10.setPixmap(QPixmap(u"Sources/Images/tesoro.jpg"))
        self.label_10.setScaledContents(True)
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(90, 180, 111, 61))
        self.label_11.setPixmap(QPixmap(u"Sources/Images/chocones.jpg"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.page_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(430, 480, 71, 16))
        self.label_12.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_13 = QLabel(self.page_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(230, 10, 391, 41))
        self.label_13.setStyleSheet(u"font-size: 18pt; font-weight: bold;")
        self.label_14 = QLabel(self.page_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(160, 100, 461, 41))
        self.label_14.setStyleSheet(u"font-size:12pt;")
        self.label_14.setWordWrap(True)
        self.label_15 = QLabel(self.page_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(70, 280, 131, 71))
        self.label_15.setPixmap(QPixmap(u"Sources/Images/motaniarusa.jpg"))
        self.label_15.setScaledContents(True)
        self.label_16 = QLabel(self.page_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(60, 380, 131, 91))
        self.label_16.setPixmap(QPixmap(u"Sources/Images/ruleta.webp"))
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.page_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(290, 440, 131, 81))
        self.label_17.setPixmap(QPixmap(u"Sources/Images/entrada.jpg"))
        self.label_17.setScaledContents(True)
        self.label_18 = QLabel(self.page_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(530, 250, 131, 81))
        self.label_18.setPixmap(QPixmap(u"Sources/Images/trenecito.jpg"))
        self.label_18.setScaledContents(True)
        self.label_19 = QLabel(self.page_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(50, 490, 141, 21))
        self.label_19.setStyleSheet(u"font-size: 12pt; font: bold")
        self.label_69 = QLabel(self.page_2)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(590, 360, 141, 21))
        self.label_69.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.btnNext_2 = QPushButton(self.page_2)
        self.btnNext_2.setObjectName(u"btnNext_2")
        self.btnNext_2.setGeometry(QRect(690, 510, 75, 24))
        self.btnNext_2.setStyleSheet(u"background-color:rgb(58,154,255)")
        VistaProfundiad.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_20 = QLabel(self.page_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(260, 440, 131, 81))
        self.label_20.setPixmap(QPixmap(u"Sources/Images/entrada.jpg"))
        self.label_20.setScaledContents(True)
        self.label_21 = QLabel(self.page_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(40, 290, 131, 71))
        self.label_21.setPixmap(QPixmap(u"Sources/Images/motaniarusa.jpg"))
        self.label_21.setScaledContents(True)
        self.label_22 = QLabel(self.page_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(520, 270, 131, 81))
        self.label_22.setPixmap(QPixmap(u"Sources/Images/trenecito.jpg"))
        self.label_22.setScaledContents(True)
        self.label_23 = QLabel(self.page_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(40, 390, 131, 91))
        self.label_23.setPixmap(QPixmap(u"Sources/Images/ruleta.webp"))
        self.label_23.setScaledContents(True)
        self.label_24 = QLabel(self.page_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(410, 480, 71, 16))
        self.label_24.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_25 = QLabel(self.page_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(600, 240, 141, 91))
        self.label_25.setPixmap(QPixmap(u"Sources/Images/tesoro.jpg"))
        self.label_25.setScaledContents(True)
        self.label_26 = QLabel(self.page_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(260, 300, 111, 61))
        self.label_26.setPixmap(QPixmap(u"Sources/Images/chocones.jpg"))
        self.label_26.setScaledContents(True)
        self.label_27 = QLabel(self.page_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(100, 80, 551, 51))
        self.label_27.setStyleSheet(u"font-size: 12pt")
        self.label_27.setWordWrap(True)
        self.label_28 = QLabel(self.page_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(60, 510, 141, 21))
        self.label_28.setStyleSheet(u"font-size: 12pt; font: bold")
        self.label_29 = QLabel(self.page_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(280, 390, 141, 21))
        self.label_29.setStyleSheet(u"font-size: 12pt; font: bold")
        self.label_30 = QLabel(self.page_3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(100, 150, 551, 51))
        self.label_30.setStyleSheet(u"font-size: 12pt")
        self.label_30.setWordWrap(True)
        self.label_64 = QLabel(self.page_3)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(200, 20, 351, 41))
        self.label_64.setStyleSheet(u"font-size: 18pt; font-weight: bold;")
        self.label_68 = QLabel(self.page_3)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(580, 370, 141, 21))
        self.label_68.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.btnNext_3 = QPushButton(self.page_3)
        self.btnNext_3.setObjectName(u"btnNext_3")
        self.btnNext_3.setGeometry(QRect(700, 500, 75, 24))
        self.btnNext_3.setStyleSheet(u"background-color:rgb(58,154,255)")
        VistaProfundiad.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_31 = QLabel(self.page_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(350, 500, 141, 21))
        self.label_31.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_32 = QLabel(self.page_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(340, 410, 111, 61))
        self.label_32.setPixmap(QPixmap(u"Sources/Images/chocones.jpg"))
        self.label_32.setScaledContents(True)
        self.label_33 = QLabel(self.page_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(340, 300, 131, 71))
        self.label_33.setPixmap(QPixmap(u"Sources/Images/motaniarusa.jpg"))
        self.label_33.setScaledContents(True)
        self.label_34 = QLabel(self.page_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(80, 400, 141, 21))
        self.label_34.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_35 = QLabel(self.page_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(630, 250, 141, 91))
        self.label_35.setPixmap(QPixmap(u"Sources/Images/tesoro.jpg"))
        self.label_35.setScaledContents(True)
        self.label_36 = QLabel(self.page_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(90, 290, 131, 91))
        self.label_36.setPixmap(QPixmap(u"Sources/Images/ruleta.webp"))
        self.label_36.setScaledContents(True)
        self.label_37 = QLabel(self.page_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(550, 280, 131, 81))
        self.label_37.setPixmap(QPixmap(u"Sources/Images/trenecito.jpg"))
        self.label_37.setScaledContents(True)
        self.label_38 = QLabel(self.page_4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(220, 490, 71, 16))
        self.label_38.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_39 = QLabel(self.page_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(70, 450, 131, 81))
        self.label_39.setPixmap(QPixmap(u"Sources/Images/entrada.jpg"))
        self.label_39.setScaledContents(True)
        self.label_40 = QLabel(self.page_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(40, 70, 701, 51))
        self.label_40.setStyleSheet(u"font-size: 12pt")
        self.label_40.setWordWrap(True)
        self.label_41 = QLabel(self.page_4)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(30, 130, 701, 51))
        self.label_41.setStyleSheet(u"font-size: 12pt")
        self.label_41.setWordWrap(True)
        self.label_42 = QLabel(self.page_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(40, 180, 701, 51))
        self.label_42.setStyleSheet(u"font-size: 12pt")
        self.label_65 = QLabel(self.page_4)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(230, 20, 351, 41))
        self.label_65.setStyleSheet(u"font-size: 18pt; font-weight: bold;")
        self.label_67 = QLabel(self.page_4)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(620, 390, 141, 21))
        self.label_67.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.btnNext_4 = QPushButton(self.page_4)
        self.btnNext_4.setObjectName(u"btnNext_4")
        self.btnNext_4.setGeometry(QRect(690, 510, 75, 24))
        self.btnNext_4.setStyleSheet(u"background-color:rgb(58,154,255)")
        VistaProfundiad.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.label_43 = QLabel(self.page_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(530, 460, 141, 21))
        self.label_43.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_44 = QLabel(self.page_5)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(70, 430, 131, 81))
        self.label_44.setPixmap(QPixmap(u"Sources/Images/entrada.jpg"))
        self.label_44.setScaledContents(True)
        self.label_45 = QLabel(self.page_5)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(50, 160, 131, 81))
        self.label_45.setPixmap(QPixmap(u"Sources/Images/trenecito.jpg"))
        self.label_45.setScaledContents(True)
        self.label_46 = QLabel(self.page_5)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(90, 260, 131, 91))
        self.label_46.setPixmap(QPixmap(u"Sources/Images/ruleta.webp"))
        self.label_46.setScaledContents(True)
        self.label_47 = QLabel(self.page_5)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(520, 260, 131, 71))
        self.label_47.setPixmap(QPixmap(u"Sources/Images/motaniarusa.jpg"))
        self.label_47.setScaledContents(True)
        self.label_48 = QLabel(self.page_5)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(220, 470, 71, 16))
        self.label_48.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_49 = QLabel(self.page_5)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(130, 130, 141, 91))
        self.label_49.setPixmap(QPixmap(u"Sources/Images/tesoro.jpg"))
        self.label_49.setScaledContents(True)
        self.label_50 = QLabel(self.page_5)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(520, 370, 111, 61))
        self.label_50.setPixmap(QPixmap(u"Sources/Images/chocones.jpg"))
        self.label_50.setScaledContents(True)
        self.label_51 = QLabel(self.page_5)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(80, 380, 141, 21))
        self.label_51.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_52 = QLabel(self.page_5)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(330, 60, 431, 121))
        self.label_52.setStyleSheet(u"font-size:12pt")
        self.label_52.setWordWrap(True)
        self.label_66 = QLabel(self.page_5)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(220, 30, 351, 41))
        self.label_66.setStyleSheet(u"font-size: 18pt; font-weight: bold;")
        self.btnNext_5 = QPushButton(self.page_5)
        self.btnNext_5.setObjectName(u"btnNext_5")
        self.btnNext_5.setGeometry(QRect(710, 490, 75, 24))
        self.btnNext_5.setStyleSheet(u"background-color:rgb(58,154,255)")
        VistaProfundiad.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.label_53 = QLabel(self.page_6)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(500, 130, 141, 91))
        self.label_53.setPixmap(QPixmap(u"Sources/Images/tesoro.jpg"))
        self.label_53.setScaledContents(True)
        self.label_54 = QLabel(self.page_6)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(230, 450, 71, 16))
        self.label_54.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_55 = QLabel(self.page_6)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(420, 160, 131, 81))
        self.label_55.setPixmap(QPixmap(u"Sources/Images/trenecito.jpg"))
        self.label_55.setScaledContents(True)
        self.label_56 = QLabel(self.page_6)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(80, 410, 131, 81))
        self.label_56.setPixmap(QPixmap(u"Sources/Images/entrada.jpg"))
        self.label_56.setScaledContents(True)
        self.label_57 = QLabel(self.page_6)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(500, 470, 141, 21))
        self.label_57.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_58 = QLabel(self.page_6)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(70, 240, 131, 91))
        self.label_58.setPixmap(QPixmap(u"Sources/Images/ruleta.webp"))
        self.label_58.setScaledContents(True)
        self.label_59 = QLabel(self.page_6)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(50, 80, 431, 61))
        self.label_59.setStyleSheet(u"font-size: 12pt")
        self.label_59.setWordWrap(True)
        self.label_60 = QLabel(self.page_6)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(490, 270, 131, 71))
        self.label_60.setPixmap(QPixmap(u"Sources/Images/motaniarusa.jpg"))
        self.label_60.setScaledContents(True)
        self.label_61 = QLabel(self.page_6)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(90, 360, 141, 21))
        self.label_61.setStyleSheet(u"font-size: 12pt; font:bold;")
        self.label_62 = QLabel(self.page_6)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(490, 380, 111, 61))
        self.label_62.setPixmap(QPixmap(u"Sources/Images/chocones.jpg"))
        self.label_62.setScaledContents(True)
        self.label_63 = QLabel(self.page_6)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(50, 150, 351, 61))
        self.label_63.setStyleSheet(u"font-size:12pt")
        self.label_63.setWordWrap(True)
        self.label_70 = QLabel(self.page_6)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(220, 20, 351, 41))
        self.label_70.setStyleSheet(u"font-size: 18pt; font-weight: bold;")
        self.btnTerminar = QPushButton(self.page_6)
        self.btnTerminar.setObjectName(u"btnTerminar")
        self.btnTerminar.setGeometry(QRect(700, 510, 75, 24))
        self.btnTerminar.setStyleSheet(u"background-color:rgb(58,154,255)")
        VistaProfundiad.addWidget(self.page_6)

        self.retranslateUi(VistaProfundiad)

        VistaProfundiad.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(VistaProfundiad)
    # setupUi

    def retranslateUi(self, VistaProfundiad):
        VistaProfundiad.setWindowTitle(QCoreApplication.translate("VistaProfundiad", u"StackedWidget", None))
        self.label.setText(QCoreApplication.translate("VistaProfundiad", u"Recorrido En Profundidad", None))
        self.label_2.setText(QCoreApplication.translate("VistaProfundiad", u"Imagina que el tesoro est\u00e1 escondido en una de las atracciones del parque, y nuestro objetivo es encontrarlo. Usaremos los pasos del recorrido en profundidad para asegurarnos de que no nos falte ning\u00fan lugar por revisar.", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.label_7.setText("")
        self.label_8.setText("")
        self.btnNext.setText(QCoreApplication.translate("VistaProfundiad", u"Siguiente", None))
        self.label_9.setText(QCoreApplication.translate("VistaProfundiad", u"Entrada", None))
        self.label_10.setText("")
        self.label_11.setText("")
        self.label_12.setText(QCoreApplication.translate("VistaProfundiad", u"Entrada", None))
        self.label_13.setText(QCoreApplication.translate("VistaProfundiad", u"Recorrido En Profundidad", None))
        self.label_14.setText(QCoreApplication.translate("VistaProfundiad", u"Guardaremos nuestras atracciones mas cercanas en nuestra pila de atracciones", None))
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_18.setText("")
        self.label_19.setText(QCoreApplication.translate("VistaProfundiad", u"Pila de atracciones", None))
        self.label_69.setText(QCoreApplication.translate("VistaProfundiad", u"Pendientes", None))
        self.btnNext_2.setText(QCoreApplication.translate("VistaProfundiad", u"Siguiente", None))
        self.label_20.setText("")
        self.label_21.setText("")
        self.label_22.setText("")
        self.label_23.setText("")
        self.label_24.setText(QCoreApplication.translate("VistaProfundiad", u"Entrada", None))
        self.label_25.setText("")
        self.label_26.setText("")
        self.label_27.setText(QCoreApplication.translate("VistaProfundiad", u"De nuestra pila de atracciones quitaremos la que tengas hasta arriba y la marcaremos como visitada", None))
        self.label_28.setText(QCoreApplication.translate("VistaProfundiad", u"Pila de atracciones ", None))
        self.label_29.setText(QCoreApplication.translate("VistaProfundiad", u"Visitadas", None))
        self.label_30.setText(QCoreApplication.translate("VistaProfundiad", u"Como en el mapa no nos marca que este atraccion este cerca de alguna atraccion quitaremos la que este mas arriba en nuestra pila", None))
        self.label_64.setText(QCoreApplication.translate("VistaProfundiad", u"Recorrido En Profundidad", None))
        self.label_68.setText(QCoreApplication.translate("VistaProfundiad", u"Pendientes", None))
        self.btnNext_3.setText(QCoreApplication.translate("VistaProfundiad", u"Siguiente", None))
        self.label_31.setText(QCoreApplication.translate("VistaProfundiad", u"Visitadas", None))
        self.label_32.setText("")
        self.label_33.setText("")
        self.label_34.setText(QCoreApplication.translate("VistaProfundiad", u"Pila de atracciones ", None))
        self.label_35.setText("")
        self.label_36.setText("")
        self.label_37.setText("")
        self.label_38.setText(QCoreApplication.translate("VistaProfundiad", u"Entrada", None))
        self.label_39.setText("")
        self.label_40.setText(QCoreApplication.translate("VistaProfundiad", u"Quitaremos de nuevo la atraccione que este mas arriba de nuestra pila de atracciones y la marcaremos como visitada", None))
        self.label_41.setText(QCoreApplication.translate("VistaProfundiad", u"Verificaremos si de esta atracciones tenemos una mas cercana, !Es asi, el trenecito esta proxima a esta!!!", None))
        self.label_42.setText(QCoreApplication.translate("VistaProfundiad", u"Agregaremos el trenecito a nuestra pila de atracciones", None))
        self.label_65.setText(QCoreApplication.translate("VistaProfundiad", u"Recorrido En Profundidad", None))
        self.label_67.setText(QCoreApplication.translate("VistaProfundiad", u"Pendientes", None))
        self.btnNext_4.setText(QCoreApplication.translate("VistaProfundiad", u"Siguiente", None))
        self.label_43.setText(QCoreApplication.translate("VistaProfundiad", u"Visitadas", None))
        self.label_44.setText("")
        self.label_45.setText("")
        self.label_46.setText("")
        self.label_47.setText("")
        self.label_48.setText(QCoreApplication.translate("VistaProfundiad", u"Entrada", None))
        self.label_49.setText("")
        self.label_50.setText("")
        self.label_51.setText(QCoreApplication.translate("VistaProfundiad", u"Pila de atracciones ", None))
        self.label_52.setText(QCoreApplication.translate("VistaProfundiad", u"Repetimos y sacamos la ultima atraccion de nuestra pila de atracciones", None))
        self.label_66.setText(QCoreApplication.translate("VistaProfundiad", u"Recorrido En Profundidad", None))
        self.btnNext_5.setText(QCoreApplication.translate("VistaProfundiad", u"Siguiente", None))
        self.label_53.setText("")
        self.label_54.setText(QCoreApplication.translate("VistaProfundiad", u"Entrada", None))
        self.label_55.setText("")
        self.label_56.setText("")
        self.label_57.setText(QCoreApplication.translate("VistaProfundiad", u"Visitadas", None))
        self.label_58.setText("")
        self.label_59.setText(QCoreApplication.translate("VistaProfundiad", u"Verificamos nuestra lista de visitados y miren!!!, ENCONTRAMOS EL TESORO!!!!!", None))
        self.label_60.setText("")
        self.label_61.setText(QCoreApplication.translate("VistaProfundiad", u"Pila de atracciones ", None))
        self.label_62.setText("")
        self.label_63.setText(QCoreApplication.translate("VistaProfundiad", u"De esta forma encontramos la ruta mas rapida para encontrar el tesoro desde nuestra entrada, sin necesidad de recorrer todo el parque", None))
        self.label_70.setText(QCoreApplication.translate("VistaProfundiad", u"Recorrido En Profundidad", None))
        self.btnTerminar.setText(QCoreApplication.translate("VistaProfundiad", u"Terminar", None))
    # retranslateUi

