# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'HeapSort.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
import os
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

script_dir = os.path.dirname(__file__)
image_path = os.path.join(script_dir,"dataestructurefordummies", "Sources", "Images", "sillon.png")

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        if not StackedWidget.objectName():
            StackedWidget.setObjectName(u"StackedWidget")
        StackedWidget.resize(761, 521)
        StackedWidget.setStyleSheet(u"background-color:rgb(255, 142, 119)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(260, 10, 241, 51))
        font = QFont()
        font.setPointSize(32)
        font.setBold(True)
        self.label.setFont(font)
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(60, 220, 191, 241))
        self.label_2.setPixmap(QPixmap(image_path))
        self.label_2.setScaledContents(True)
        self.btnNext = QPushButton(self.page)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(660, 480, 75, 24))
        self.btnNext.setStyleSheet(u"background-color:rgb(232, 119, 21)")
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 70, 551, 151))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(400, 400, 61, 41))
        self.label_4.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(400, 335, 71, 41))
        self.label_5.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_5.setScaledContents(True)
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(490, 385, 81, 61))
        self.label_6.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.page)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(490, 275, 81, 91))
        self.label_7.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(self.page)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(590, 330, 81, 111))
        self.label_8.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_8.setScaledContents(True)
        self.label_9 = QLabel(self.page)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(290, 310, 81, 71))
        font2 = QFont()
        font2.setPointSize(28)
        font2.setBold(True)
        self.label_9.setFont(font2)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.btnNext_2 = QPushButton(self.page_2)
        self.btnNext_2.setObjectName(u"btnNext_2")
        self.btnNext_2.setGeometry(QRect(660, 480, 75, 24))
        self.btnNext_2.setStyleSheet(u"background-color:rgb(232, 119, 21)")
        self.label_10 = QLabel(self.page_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(260, 10, 241, 51))
        self.label_10.setFont(font)
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(80, 60, 601, 151))
        self.label_11.setFont(font1)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_12 = QLabel(self.page_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 190, 251, 331))
        self.label_12.setPixmap(QPixmap(u"../Sources/Images/sillon.png"))
        self.label_12.setScaledContents(True)
        self.label_13 = QLabel(self.page_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(120, 360, 81, 61))
        self.label_13.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_13.setScaledContents(True)
        self.label_14 = QLabel(self.page_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(170, 330, 71, 41))
        self.label_14.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.page_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(60, 360, 61, 41))
        self.label_15.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_15.setScaledContents(True)
        self.label_16 = QLabel(self.page_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(160, 220, 81, 111))
        self.label_16.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.page_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(90, 270, 81, 91))
        self.label_17.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_17.setScaledContents(True)
        self.label_18 = QLabel(self.page_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(280, 300, 81, 71))
        self.label_18.setFont(font2)
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_19 = QLabel(self.page_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(670, 290, 51, 81))
        self.label_19.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_19.setScaledContents(True)
        self.label_20 = QLabel(self.page_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(360, 270, 371, 121))
        self.label_20.setPixmap(QPixmap(u"../Sources/Images/mueble.png"))
        self.label_20.setScaledContents(True)
        StackedWidget.addWidget(self.page_2)
        self.btnNext_2.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_20.raise_()
        self.label_19.raise_()
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.btnNext_3 = QPushButton(self.page_3)
        self.btnNext_3.setObjectName(u"btnNext_3")
        self.btnNext_3.setGeometry(QRect(660, 480, 75, 24))
        self.btnNext_3.setStyleSheet(u"background-color:rgb(232, 119, 21)")
        self.label_21 = QLabel(self.page_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(260, 10, 241, 51))
        self.label_21.setFont(font)
        self.label_22 = QLabel(self.page_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(70, 60, 601, 151))
        self.label_22.setFont(font1)
        self.label_22.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_23 = QLabel(self.page_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(120, 330, 81, 61))
        self.label_23.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_23.setScaledContents(True)
        self.label_24 = QLabel(self.page_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(60, 330, 61, 41))
        self.label_24.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_24.setScaledContents(True)
        self.label_25 = QLabel(self.page_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(280, 270, 81, 71))
        self.label_25.setFont(font2)
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_26 = QLabel(self.page_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(30, 180, 251, 311))
        self.label_26.setPixmap(QPixmap(u"../Sources/Images/sillon.png"))
        self.label_26.setScaledContents(True)
        self.label_28 = QLabel(self.page_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(110, 200, 81, 91))
        self.label_28.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_28.setScaledContents(True)
        self.label_29 = QLabel(self.page_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(80, 290, 71, 41))
        self.label_29.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_29.setScaledContents(True)
        self.label_30 = QLabel(self.page_3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(90, 330, 61, 41))
        self.label_30.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_30.setScaledContents(True)
        self.label_31 = QLabel(self.page_3)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(150, 290, 81, 61))
        self.label_31.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_31.setScaledContents(True)
        self.label_27 = QLabel(self.page_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(670, 280, 51, 81))
        self.label_27.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_27.setScaledContents(True)
        self.label_32 = QLabel(self.page_3)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(360, 260, 371, 121))
        self.label_32.setPixmap(QPixmap(u"../Sources/Images/mueble.png"))
        self.label_32.setScaledContents(True)
        self.label_33 = QLabel(self.page_3)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(600, 290, 51, 71))
        self.label_33.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_33.setScaledContents(True)
        StackedWidget.addWidget(self.page_3)
        self.btnNext_3.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_27.raise_()
        self.label_33.raise_()
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_34 = QLabel(self.page_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(260, 10, 241, 51))
        self.label_34.setFont(font)
        self.label_35 = QLabel(self.page_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(20, 170, 251, 311))
        self.label_35.setPixmap(QPixmap(u"../Sources/Images/sillon.png"))
        self.label_35.setScaledContents(True)
        self.label_36 = QLabel(self.page_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(360, 250, 371, 121))
        self.label_36.setPixmap(QPixmap(u"../Sources/Images/mueble.png"))
        self.label_36.setScaledContents(True)
        self.btnNext_4 = QPushButton(self.page_4)
        self.btnNext_4.setObjectName(u"btnNext_4")
        self.btnNext_4.setGeometry(QRect(660, 480, 75, 24))
        self.btnNext_4.setStyleSheet(u"background-color:rgb(232, 119, 21)")
        self.label_37 = QLabel(self.page_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(70, 60, 601, 151))
        self.label_37.setFont(font1)
        self.label_37.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_38 = QLabel(self.page_4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(670, 280, 51, 81))
        self.label_38.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_38.setScaledContents(True)
        self.label_39 = QLabel(self.page_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(600, 290, 51, 71))
        self.label_39.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_39.setScaledContents(True)
        self.label_40 = QLabel(self.page_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(100, 250, 81, 61))
        self.label_40.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_40.setScaledContents(True)
        self.label_41 = QLabel(self.page_4)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(70, 310, 61, 41))
        self.label_41.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_41.setScaledContents(True)
        self.label_42 = QLabel(self.page_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(140, 310, 71, 41))
        self.label_42.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_42.setScaledContents(True)
        self.label_43 = QLabel(self.page_4)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(270, 280, 81, 71))
        self.label_43.setFont(font2)
        self.label_43.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_44 = QLabel(self.page_4)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(530, 310, 51, 51))
        self.label_44.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_44.setScaledContents(True)
        StackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.label_45 = QLabel(self.page_5)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(600, 260, 51, 71))
        self.label_45.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_45.setScaledContents(True)
        self.label_46 = QLabel(self.page_5)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(530, 280, 51, 51))
        self.label_46.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_46.setScaledContents(True)
        self.label_47 = QLabel(self.page_5)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(20, 150, 251, 311))
        self.label_47.setPixmap(QPixmap(u"../Sources/Images/sillon.png"))
        self.label_47.setScaledContents(True)
        self.label_48 = QLabel(self.page_5)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(670, 250, 51, 81))
        self.label_48.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_48.setScaledContents(True)
        self.btnNext_5 = QPushButton(self.page_5)
        self.btnNext_5.setObjectName(u"btnNext_5")
        self.btnNext_5.setGeometry(QRect(660, 480, 75, 24))
        self.btnNext_5.setStyleSheet(u"background-color:rgb(232, 119, 21)")
        self.label_49 = QLabel(self.page_5)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(260, 10, 241, 51))
        self.label_49.setFont(font)
        self.label_50 = QLabel(self.page_5)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(360, 230, 371, 121))
        self.label_50.setPixmap(QPixmap(u"../Sources/Images/mueble.png"))
        self.label_50.setScaledContents(True)
        self.label_51 = QLabel(self.page_5)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(110, 240, 71, 41))
        self.label_51.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_51.setScaledContents(True)
        self.label_52 = QLabel(self.page_5)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(110, 280, 61, 41))
        self.label_52.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_52.setScaledContents(True)
        self.label_53 = QLabel(self.page_5)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(270, 250, 81, 71))
        self.label_53.setFont(font2)
        self.label_53.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_54 = QLabel(self.page_5)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(80, 60, 601, 151))
        self.label_54.setFont(font1)
        self.label_54.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_55 = QLabel(self.page_5)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(460, 290, 51, 31))
        self.label_55.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_55.setScaledContents(True)
        StackedWidget.addWidget(self.page_5)
        self.label_47.raise_()
        self.btnNext_5.raise_()
        self.label_49.raise_()
        self.label_50.raise_()
        self.label_46.raise_()
        self.label_45.raise_()
        self.label_48.raise_()
        self.label_51.raise_()
        self.label_52.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.btnTermiando = QPushButton(self.page_6)
        self.btnTermiando.setObjectName(u"btnTermiando")
        self.btnTermiando.setGeometry(QRect(310, 430, 141, 51))
        self.btnTermiando.setStyleSheet(u"background-color:rgb(232, 119, 21)")
        self.label_56 = QLabel(self.page_6)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(260, 270, 81, 71))
        self.label_56.setFont(font2)
        self.label_56.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_57 = QLabel(self.page_6)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(80, 60, 601, 151))
        self.label_57.setFont(font1)
        self.label_57.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_58 = QLabel(self.page_6)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(40, 180, 231, 291))
        self.label_58.setPixmap(QPixmap(u"../Sources/Images/sillon.png"))
        self.label_58.setScaledContents(True)
        self.label_59 = QLabel(self.page_6)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(350, 250, 371, 121))
        self.label_59.setPixmap(QPixmap(u"../Sources/Images/mueble.png"))
        self.label_59.setScaledContents(True)
        self.label_60 = QLabel(self.page_6)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(260, 10, 241, 51))
        self.label_60.setFont(font)
        self.label_61 = QLabel(self.page_6)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(520, 300, 51, 51))
        self.label_61.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_61.setScaledContents(True)
        self.label_62 = QLabel(self.page_6)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(450, 310, 51, 41))
        self.label_62.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_62.setScaledContents(True)
        self.label_63 = QLabel(self.page_6)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(590, 280, 51, 71))
        self.label_63.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_63.setScaledContents(True)
        self.label_64 = QLabel(self.page_6)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(650, 270, 51, 81))
        self.label_64.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_64.setScaledContents(True)
        self.label_65 = QLabel(self.page_6)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(380, 320, 51, 31))
        self.label_65.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_65.setScaledContents(True)
        StackedWidget.addWidget(self.page_6)

        self.retranslateUi(StackedWidget)

        StackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(StackedWidget)
    # setupUi

    def retranslateUi(self, StackedWidget):
        StackedWidget.setWindowTitle(QCoreApplication.translate("StackedWidget", u"StackedWidget", None))
        self.label.setText(QCoreApplication.translate("StackedWidget", u"HEAP SORT", None))
        self.label_2.setText("")
        self.btnNext.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_3.setText(QCoreApplication.translate("StackedWidget", u"Imagina que otra vez debemos ordenar tus juguetes,pero \n"
"esta vez tienes un sill\u00f3n vacio que puedes utilizar ayudarte.\n"
" Ahora ocuparemos el HEAP SORT, y para esto lo primero que haremos\n"
"ser\u00e1 acomodar todos tus juguetes en el sill\u00f3n.\n"
"PERO OJO, debes poner el mas grande hasta arriba de todos los juguetes", None))
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.label_7.setText("")
        self.label_8.setText("")
        self.label_9.setText(QCoreApplication.translate("StackedWidget", u"<-", None))
        self.btnNext_2.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_10.setText(QCoreApplication.translate("StackedWidget", u"HEAP SORT", None))
        self.label_11.setText(QCoreApplication.translate("StackedWidget", u"Ahora, de la monta\u00f1a magica que hicimos en el sill\u00f3n, vamos a quitar \n"
"el juguete de hasta arriba para ponerlo en el lugar donde lo vamos a guardar.", None))
        self.label_12.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_18.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_19.setText("")
        self.label_20.setText("")
        self.btnNext_3.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_21.setText(QCoreApplication.translate("StackedWidget", u"HEAP SORT", None))
        self.label_22.setText(QCoreApplication.translate("StackedWidget", u"Ya ordenamos el primer juguete, pero ahora en \n"
"el sill\u00f3n debemos poner hasta arriba, el nuevo juegute mas grande. una \n"
"vez que lo pongamos y sepamos c\u00faal es, otra vez sacaremos ese juguete del \n"
"sill\u00f3n para ponerlo en el mueble", None))
        self.label_23.setText("")
        self.label_24.setText("")
        self.label_25.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_26.setText("")
        self.label_28.setText("")
        self.label_29.setText("")
        self.label_30.setText("")
        self.label_31.setText("")
        self.label_27.setText("")
        self.label_32.setText("")
        self.label_33.setText("")
        self.label_34.setText(QCoreApplication.translate("StackedWidget", u"HEAP SORT", None))
        self.label_35.setText("")
        self.label_36.setText("")
        self.btnNext_4.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_37.setText(QCoreApplication.translate("StackedWidget", u"Repetimos el proceso.\n"
"Ordenamos el sillon poniendo el nuevo juguete mas grande hasta arriba. \n"
"Debemos sacar el mas grande del sill\u00f3n para ponerlo en el mueble.", None))
        self.label_38.setText("")
        self.label_39.setText("")
        self.label_40.setText("")
        self.label_41.setText("")
        self.label_42.setText("")
        self.label_43.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_44.setText("")
        self.label_45.setText("")
        self.label_46.setText("")
        self.label_47.setText("")
        self.label_48.setText("")
        self.btnNext_5.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_49.setText(QCoreApplication.translate("StackedWidget", u"HEAP SORT", None))
        self.label_50.setText("")
        self.label_51.setText("")
        self.label_52.setText("")
        self.label_53.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_54.setText(QCoreApplication.translate("StackedWidget", u"Repetimos el proceso.\n"
"Ordenamos el sillon poniendo el nuevo juguete mas grande hasta arriba. \n"
"Debemos sacar el mas grande del sill\u00f3n para ponerlo en el mueble.", None))
        self.label_55.setText("")
        self.btnTermiando.setText(QCoreApplication.translate("StackedWidget", u"TERMINADO", None))
        self.label_56.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_57.setText(QCoreApplication.translate("StackedWidget", u"Una vez que ya no tengamos nada en el sill\u00f3n \n"
"y metamos todos nuestros juguetes en el mueble\n"
"Habremos acabado de ordenar con nuestro amigo HEAP SORT.\n"
"\u00bfQu\u00e9 te pareci\u00f3 este m\u00e9todo? \n"
"\u00bfTe gust\u00f3?", None))
        self.label_58.setText("")
        self.label_59.setText("")
        self.label_60.setText(QCoreApplication.translate("StackedWidget", u"HEAP SORT", None))
        self.label_61.setText("")
        self.label_62.setText("")
        self.label_63.setText("")
        self.label_64.setText("")
        self.label_65.setText("")
    # retranslateUi

