# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MergeSort.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        if not StackedWidget.objectName():
            StackedWidget.setObjectName(u"StackedWidget")
        StackedWidget.resize(761, 521)
        StackedWidget.setStyleSheet(u"background-color:rgb(245, 199, 134)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 20, 311, 41))
        font = QFont()
        font.setFamilies([u"Caprasimo"])
        font.setPointSize(32)
        font.setBold(False)
        self.label.setFont(font)
        self.numero5 = QPushButton(self.page)
        self.numero5.setObjectName(u"numero5")
        self.numero5.setGeometry(QRect(110, 380, 151, 51))
        font1 = QFont()
        font1.setPointSize(24)
        font1.setBold(True)
        self.numero5.setFont(font1)
        self.numero5.setStyleSheet(u"background-color:red")
        self.numero1 = QPushButton(self.page)
        self.numero1.setObjectName(u"numero1")
        self.numero1.setGeometry(QRect(110, 330, 151, 51))
        self.numero1.setFont(font1)
        self.numero1.setStyleSheet(u"background-color:green")
        self.numero4 = QPushButton(self.page)
        self.numero4.setObjectName(u"numero4")
        self.numero4.setGeometry(QRect(110, 230, 151, 51))
        self.numero4.setFont(font1)
        self.numero4.setStyleSheet(u"background-color:purple")
        self.numero3 = QPushButton(self.page)
        self.numero3.setObjectName(u"numero3")
        self.numero3.setGeometry(QRect(110, 280, 151, 51))
        self.numero3.setFont(font1)
        self.numero3.setStyleSheet(u"background-color:orange")
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 100, 661, 91))
        font2 = QFont()
        font2.setFamilies([u"Caprasimo"])
        font2.setPointSize(12)
        font2.setBold(False)
        self.label_2.setFont(font2)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(270, 290, 71, 61))
        font3 = QFont()
        font3.setPointSize(48)
        font3.setBold(True)
        self.label_3.setFont(font3)
        self.numero4_2 = QPushButton(self.page)
        self.numero4_2.setObjectName(u"numero4_2")
        self.numero4_2.setGeometry(QRect(540, 290, 151, 51))
        self.numero4_2.setFont(font1)
        self.numero4_2.setStyleSheet(u"background-color:purple")
        self.numero1_2 = QPushButton(self.page)
        self.numero1_2.setObjectName(u"numero1_2")
        self.numero1_2.setGeometry(QRect(370, 290, 151, 51))
        self.numero1_2.setFont(font1)
        self.numero1_2.setStyleSheet(u"background-color:green")
        self.numero5_2 = QPushButton(self.page)
        self.numero5_2.setObjectName(u"numero5_2")
        self.numero5_2.setGeometry(QRect(370, 340, 151, 51))
        self.numero5_2.setFont(font1)
        self.numero5_2.setStyleSheet(u"background-color:red")
        self.numero3_2 = QPushButton(self.page)
        self.numero3_2.setObjectName(u"numero3_2")
        self.numero3_2.setGeometry(QRect(540, 340, 151, 51))
        self.numero3_2.setFont(font1)
        self.numero3_2.setStyleSheet(u"background-color:orange")
        self.btnNext = QPushButton(self.page)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(660, 480, 75, 24))
        self.btnNext.setStyleSheet(u"background-color:rgb(108, 88, 59)")
        StackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(60, 70, 651, 91))
        self.label_5.setFont(font2)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.numero5_3 = QPushButton(self.page_2)
        self.numero5_3.setObjectName(u"numero5_3")
        self.numero5_3.setGeometry(QRect(30, 260, 151, 51))
        self.numero5_3.setFont(font1)
        self.numero5_3.setStyleSheet(u"background-color:red")
        self.numero3_3 = QPushButton(self.page_2)
        self.numero3_3.setObjectName(u"numero3_3")
        self.numero3_3.setGeometry(QRect(30, 330, 151, 51))
        self.numero3_3.setFont(font1)
        self.numero3_3.setStyleSheet(u"background-color:orange")
        self.numero1_3 = QPushButton(self.page_2)
        self.numero1_3.setObjectName(u"numero1_3")
        self.numero1_3.setGeometry(QRect(30, 190, 151, 51))
        self.numero1_3.setFont(font1)
        self.numero1_3.setStyleSheet(u"background-color:green")
        self.numero4_3 = QPushButton(self.page_2)
        self.numero4_3.setObjectName(u"numero4_3")
        self.numero4_3.setGeometry(QRect(30, 400, 151, 51))
        self.numero4_3.setFont(font1)
        self.numero4_3.setStyleSheet(u"background-color:purple")
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(200, 210, 71, 61))
        self.label_6.setFont(font3)
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(200, 350, 71, 61))
        self.label_7.setFont(font3)
        self.numero1_4 = QPushButton(self.page_2)
        self.numero1_4.setObjectName(u"numero1_4")
        self.numero1_4.setGeometry(QRect(300, 200, 151, 51))
        self.numero1_4.setFont(font1)
        self.numero1_4.setStyleSheet(u"background-color:green")
        self.numero5_4 = QPushButton(self.page_2)
        self.numero5_4.setObjectName(u"numero5_4")
        self.numero5_4.setGeometry(QRect(300, 250, 151, 51))
        self.numero5_4.setFont(font1)
        self.numero5_4.setStyleSheet(u"background-color:red")
        self.numero3_4 = QPushButton(self.page_2)
        self.numero3_4.setObjectName(u"numero3_4")
        self.numero3_4.setGeometry(QRect(300, 340, 151, 51))
        self.numero3_4.setFont(font1)
        self.numero3_4.setStyleSheet(u"background-color:orange")
        self.numero4_4 = QPushButton(self.page_2)
        self.numero4_4.setObjectName(u"numero4_4")
        self.numero4_4.setGeometry(QRect(300, 390, 151, 51))
        self.numero4_4.setFont(font1)
        self.numero4_4.setStyleSheet(u"background-color:purple")
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(460, 200, 261, 91))
        self.label_8.setFont(font2)
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(470, 340, 261, 91))
        self.label_9.setFont(font2)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_2 = QPushButton(self.page_2)
        self.btnNext_2.setObjectName(u"btnNext_2")
        self.btnNext_2.setGeometry(QRect(660, 480, 75, 24))
        self.btnNext_2.setStyleSheet(u"background-color:rgb(108, 88, 59)")
        self.label_4 = QLabel(self.page_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(230, 20, 311, 41))
        self.label_4.setFont(font)
        StackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.btnNext_3 = QPushButton(self.page_3)
        self.btnNext_3.setObjectName(u"btnNext_3")
        self.btnNext_3.setGeometry(QRect(660, 480, 75, 24))
        self.btnNext_3.setStyleSheet(u"background-color:rgb(108, 88, 59)")
        self.label_11 = QLabel(self.page_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(60, 80, 631, 91))
        self.label_11.setFont(font2)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.numero1_5 = QPushButton(self.page_3)
        self.numero1_5.setObjectName(u"numero1_5")
        self.numero1_5.setGeometry(QRect(50, 270, 151, 51))
        self.numero1_5.setFont(font1)
        self.numero1_5.setStyleSheet(u"background-color:green")
        self.numero3_5 = QPushButton(self.page_3)
        self.numero3_5.setObjectName(u"numero3_5")
        self.numero3_5.setGeometry(QRect(50, 410, 151, 51))
        self.numero3_5.setFont(font1)
        self.numero3_5.setStyleSheet(u"background-color:orange")
        self.numero4_5 = QPushButton(self.page_3)
        self.numero4_5.setObjectName(u"numero4_5")
        self.numero4_5.setGeometry(QRect(50, 360, 151, 51))
        self.numero4_5.setFont(font1)
        self.numero4_5.setStyleSheet(u"background-color:purple")
        self.numero5_5 = QPushButton(self.page_3)
        self.numero5_5.setObjectName(u"numero5_5")
        self.numero5_5.setGeometry(QRect(50, 220, 151, 51))
        self.numero5_5.setFont(font1)
        self.numero5_5.setStyleSheet(u"background-color:red")
        self.label_12 = QLabel(self.page_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(210, 300, 71, 61))
        self.label_12.setFont(font3)
        self.numero3_6 = QPushButton(self.page_3)
        self.numero3_6.setObjectName(u"numero3_6")
        self.numero3_6.setGeometry(QRect(300, 390, 151, 51))
        self.numero3_6.setFont(font1)
        self.numero3_6.setStyleSheet(u"background-color:orange")
        self.numero5_6 = QPushButton(self.page_3)
        self.numero5_6.setObjectName(u"numero5_6")
        self.numero5_6.setGeometry(QRect(300, 240, 151, 51))
        self.numero5_6.setFont(font1)
        self.numero5_6.setStyleSheet(u"background-color:red")
        self.numero4_6 = QPushButton(self.page_3)
        self.numero4_6.setObjectName(u"numero4_6")
        self.numero4_6.setGeometry(QRect(300, 340, 151, 51))
        self.numero4_6.setFont(font1)
        self.numero4_6.setStyleSheet(u"background-color:purple")
        self.numero1_6 = QPushButton(self.page_3)
        self.numero1_6.setObjectName(u"numero1_6")
        self.numero1_6.setGeometry(QRect(300, 290, 151, 51))
        self.numero1_6.setFont(font1)
        self.numero1_6.setStyleSheet(u"background-color:green")
        self.label_13 = QLabel(self.page_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(470, 210, 261, 221))
        self.label_13.setFont(font2)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_10 = QLabel(self.page_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(230, 20, 311, 41))
        self.label_10.setFont(font)
        StackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.btnNext_4 = QPushButton(self.page_4)
        self.btnNext_4.setObjectName(u"btnNext_4")
        self.btnNext_4.setGeometry(QRect(300, 440, 151, 51))
        font4 = QFont()
        font4.setFamilies([u"Caprasimo"])
        self.btnNext_4.setFont(font4)
        self.btnNext_4.setStyleSheet(u"background-color:rgb(108, 88, 59)")
        self.label_15 = QLabel(self.page_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(60, 70, 631, 121))
        font5 = QFont()
        font5.setFamilies([u"Caprasimo"])
        font5.setPointSize(12)
        font5.setBold(True)
        self.label_15.setFont(font5)
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.numero1_7 = QPushButton(self.page_4)
        self.numero1_7.setObjectName(u"numero1_7")
        self.numero1_7.setGeometry(QRect(300, 350, 151, 51))
        self.numero1_7.setFont(font1)
        self.numero1_7.setStyleSheet(u"background-color:green")
        self.numero4_7 = QPushButton(self.page_4)
        self.numero4_7.setObjectName(u"numero4_7")
        self.numero4_7.setGeometry(QRect(300, 250, 151, 51))
        self.numero4_7.setFont(font1)
        self.numero4_7.setStyleSheet(u"background-color:purple")
        self.numero5_7 = QPushButton(self.page_4)
        self.numero5_7.setObjectName(u"numero5_7")
        self.numero5_7.setGeometry(QRect(300, 200, 151, 51))
        self.numero5_7.setFont(font1)
        self.numero5_7.setStyleSheet(u"background-color:red")
        self.numero3_7 = QPushButton(self.page_4)
        self.numero3_7.setObjectName(u"numero3_7")
        self.numero3_7.setGeometry(QRect(300, 300, 151, 51))
        self.numero3_7.setFont(font1)
        self.numero3_7.setStyleSheet(u"background-color:orange")
        self.label_14 = QLabel(self.page_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(230, 20, 311, 41))
        self.label_14.setFont(font)
        StackedWidget.addWidget(self.page_4)

        self.retranslateUi(StackedWidget)

        StackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(StackedWidget)
    # setupUi

    def retranslateUi(self, StackedWidget):
        StackedWidget.setWindowTitle(QCoreApplication.translate("StackedWidget", u"StackedWidget", None))
        self.label.setText(QCoreApplication.translate("StackedWidget", u"MERGE SORT", None))
        self.numero5.setText(QCoreApplication.translate("StackedWidget", u"5", None))
        self.numero1.setText(QCoreApplication.translate("StackedWidget", u"1", None))
        self.numero4.setText(QCoreApplication.translate("StackedWidget", u"4", None))
        self.numero3.setText(QCoreApplication.translate("StackedWidget", u"3", None))
        self.label_2.setText(QCoreApplication.translate("StackedWidget", u"Imagina que tienes una torre de bloques, y queremos ordenarlos del mas peque\u00f1o\n"
" al mas grande.Ahora usaremos el MERGE SORT para ayudarte a ordenarlos. \n"
"Lo primero que haremos ser\u00e1 dividir en dos grupos, y de esos grupos, \n"
"de nuevo dividirlos hasta que esten en grupos de 1. ", None))
        self.label_3.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.numero4_2.setText(QCoreApplication.translate("StackedWidget", u"4", None))
        self.numero1_2.setText(QCoreApplication.translate("StackedWidget", u"1", None))
        self.numero5_2.setText(QCoreApplication.translate("StackedWidget", u"5", None))
        self.numero3_2.setText(QCoreApplication.translate("StackedWidget", u"3", None))
        self.btnNext.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_5.setText(QCoreApplication.translate("StackedWidget", u"Ya que tenemos los bloques dividos en grupos de 1,\u00a1Aqui viene lo divertido! \n"
"Vamos a juntarlos de 2 en 2, PERO, vamos a ordenarlos para tenerlos listos para \n"
"guardarlos. Juntaremos dos bloques, y nos preguntaremos:\n"
"", None))
        self.numero5_3.setText(QCoreApplication.translate("StackedWidget", u"5", None))
        self.numero3_3.setText(QCoreApplication.translate("StackedWidget", u"3", None))
        self.numero1_3.setText(QCoreApplication.translate("StackedWidget", u"1", None))
        self.numero4_3.setText(QCoreApplication.translate("StackedWidget", u"4", None))
        self.label_6.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.label_7.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.numero1_4.setText(QCoreApplication.translate("StackedWidget", u"1", None))
        self.numero5_4.setText(QCoreApplication.translate("StackedWidget", u"5", None))
        self.numero3_4.setText(QCoreApplication.translate("StackedWidget", u"3", None))
        self.numero4_4.setText(QCoreApplication.translate("StackedWidget", u"4", None))
        self.label_8.setText(QCoreApplication.translate("StackedWidget", u"\u00bfQu\u00e9 n\u00famero es m\u00e1s grande? \n"
"\u00bfEl 5 o el 1? \n"
"El mas grande ir\u00e1 arriba", None))
        self.label_9.setText(QCoreApplication.translate("StackedWidget", u"\u00bfQu\u00e9 n\u00famero es mas grande? \n"
"\u00bfEl 3 o el 4? \n"
"El mas grande ir\u00e1 arriba", None))
        self.btnNext_2.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_4.setText(QCoreApplication.translate("StackedWidget", u"MERGE SORT", None))
        self.btnNext_3.setText(QCoreApplication.translate("StackedWidget", u"SIGUIENTE", None))
        self.label_11.setText(QCoreApplication.translate("StackedWidget", u"Ya que sabemos cual n\u00famero es mas grande, hay que moverlos.\n"
"Ahora tenemos los dos grupos ordenados, \u00a1LOS VOLVEMOS A JUNTAR!\n"
"Pero a\u00fan no est\u00e1n ordenados, debemos hacernos una cosa m\u00e1s. ", None))
        self.numero1_5.setText(QCoreApplication.translate("StackedWidget", u"1", None))
        self.numero3_5.setText(QCoreApplication.translate("StackedWidget", u"3", None))
        self.numero4_5.setText(QCoreApplication.translate("StackedWidget", u"4", None))
        self.numero5_5.setText(QCoreApplication.translate("StackedWidget", u"5", None))
        self.label_12.setText(QCoreApplication.translate("StackedWidget", u"->", None))
        self.numero3_6.setText(QCoreApplication.translate("StackedWidget", u"3", None))
        self.numero5_6.setText(QCoreApplication.translate("StackedWidget", u"5", None))
        self.numero4_6.setText(QCoreApplication.translate("StackedWidget", u"4", None))
        self.numero1_6.setText(QCoreApplication.translate("StackedWidget", u"1", None))
        self.label_13.setText(QCoreApplication.translate("StackedWidget", u"Ordenaremos los bloques d\u00f3nde \n"
"el m\u00e1s peque\u00f1o va hasta abajo y\n"
" el m\u00e1s grande hasta arriba.\n"
"\u00bfQu\u00e9 n\u00famero va primero?\n"
" Exacto el 1, \n"
"\u00bfDespues? \n"
" Bien, el 3\n"
"\u00bfY luego?\n"
" El 4\n"
" Y para acabar el 5.", None))
        self.label_10.setText(QCoreApplication.translate("StackedWidget", u"MERGE SORT", None))
        self.btnNext_4.setText(QCoreApplication.translate("StackedWidget", u"TERMINADO", None))
        self.label_15.setText(QCoreApplication.translate("StackedWidget", u"!YA QUEDARON ORDENADOS LOS BLOQUES!\n"
" Ahora ya los podemos meter a su caja y\n"
" tu mam\u00e1 no puede rega\u00f1arte.\n"
"Gracias MERGE SORT por la ayuda.\n"
" \u00bfQu\u00e9 te parecio?", None))
        self.numero1_7.setText(QCoreApplication.translate("StackedWidget", u"1", None))
        self.numero4_7.setText(QCoreApplication.translate("StackedWidget", u"4", None))
        self.numero5_7.setText(QCoreApplication.translate("StackedWidget", u"5", None))
        self.numero3_7.setText(QCoreApplication.translate("StackedWidget", u"3", None))
        self.label_14.setText(QCoreApplication.translate("StackedWidget", u"MERGE SORT", None))
    # retranslateUi

