# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Quicksort.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        if not StackedWidget.objectName():
            StackedWidget.setObjectName(u"StackedWidget")
        StackedWidget.resize(761, 521)
        StackedWidget.setStyleSheet(u"background-color:rgb(255, 170, 255)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(260, 20, 241, 41))
        font = QFont()
        font.setPointSize(32)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"background-color:transparent;\n"
"")
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 90, 651, 111))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(190, 310, 121, 71))
        self.label_3.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(440, 300, 151, 81))
        self.label_4.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(320, 280, 111, 101))
        self.label_5.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_5.setScaledContents(True)
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(600, 250, 91, 131))
        self.label_6.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.page)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(60, 220, 121, 161))
        self.label_7.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(self.page)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(80, 390, 601, 51))
        self.label_8.setFont(font1)
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext = QPushButton(self.page)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(640, 470, 75, 24))
        self.btnNext.setStyleSheet(u"background-color: rgb(150,45,255)")
        StackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(260, 20, 241, 41))
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(u"background-color:transparent;\n"
"")
        self.label_10 = QLabel(self.page_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(100, 80, 581, 71))
        self.label_10.setFont(font1)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(320, 180, 141, 131))
        self.label_11.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.page_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(90, 360, 581, 71))
        self.label_12.setFont(font1)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_2 = QPushButton(self.page_2)
        self.btnNext_2.setObjectName(u"btnNext_2")
        self.btnNext_2.setGeometry(QRect(650, 470, 75, 24))
        self.btnNext_2.setStyleSheet(u"background-color: rgb(150,45,255)")
        StackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_13 = QLabel(self.page_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(260, 20, 241, 41))
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(u"background-color:transparent;\n"
"")
        self.label_14 = QLabel(self.page_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(70, 140, 111, 101))
        self.label_14.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.page_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(430, 340, 111, 101))
        self.label_15.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_15.setScaledContents(True)
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(430, 140, 111, 101))
        self.label_16.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.page_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(70, 340, 111, 101))
        self.label_17.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_17.setScaledContents(True)
        self.label_18 = QLabel(self.page_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(190, 80, 121, 161))
        self.label_18.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_18.setScaledContents(True)
        self.label_19 = QLabel(self.page_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(190, 370, 121, 71))
        self.label_19.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_19.setScaledContents(True)
        self.label_20 = QLabel(self.page_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(550, 160, 151, 81))
        self.label_20.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_20.setScaledContents(True)
        self.label_21 = QLabel(self.page_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(550, 310, 91, 131))
        self.label_21.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_21.setScaledContents(True)
        self.label_22 = QLabel(self.page_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 250, 331, 51))
        self.label_22.setFont(font1)
        self.label_22.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_23 = QLabel(self.page_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(410, 250, 331, 51))
        self.label_23.setFont(font1)
        self.label_23.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_24 = QLabel(self.page_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 440, 331, 51))
        self.label_24.setFont(font1)
        self.label_24.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_25 = QLabel(self.page_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(370, 440, 331, 51))
        self.label_25.setFont(font1)
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_3 = QPushButton(self.page_3)
        self.btnNext_3.setObjectName(u"btnNext_3")
        self.btnNext_3.setGeometry(QRect(670, 480, 75, 24))
        self.btnNext_3.setStyleSheet(u"background-color: rgb(150,45,255)")
        StackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_26 = QLabel(self.page_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(260, 20, 241, 41))
        self.label_26.setFont(font)
        self.label_26.setStyleSheet(u"background-color:transparent;\n"
"")
        self.label_27 = QLabel(self.page_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(470, 290, 121, 161))
        self.label_27.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_27.setScaledContents(True)
        self.label_28 = QLabel(self.page_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(190, 370, 151, 81))
        self.label_28.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_28.setScaledContents(True)
        self.label_29 = QLabel(self.page_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(60, 380, 121, 71))
        self.label_29.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_29.setScaledContents(True)
        self.label_30 = QLabel(self.page_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(600, 320, 91, 131))
        self.label_30.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_30.setScaledContents(True)
        self.label_31 = QLabel(self.page_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(350, 350, 111, 101))
        self.label_31.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_31.setScaledContents(True)
        self.label_32 = QLabel(self.page_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(60, 70, 641, 101))
        self.label_32.setFont(font1)
        self.label_32.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_33 = QLabel(self.page_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(50, 180, 641, 81))
        self.label_33.setFont(font1)
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_4 = QPushButton(self.page_4)
        self.btnNext_4.setObjectName(u"btnNext_4")
        self.btnNext_4.setGeometry(QRect(650, 480, 75, 24))
        self.btnNext_4.setStyleSheet(u"background-color: rgb(150,45,255)")
        StackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.label_34 = QLabel(self.page_5)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(260, 20, 241, 41))
        self.label_34.setFont(font)
        self.label_34.setStyleSheet(u"background-color:transparent;\n"
"")
        self.label_35 = QLabel(self.page_5)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(200, 180, 151, 81))
        self.label_35.setPixmap(QPixmap(u"../Sources/Images/carro.png"))
        self.label_35.setScaledContents(True)
        self.label_36 = QLabel(self.page_5)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(360, 160, 111, 101))
        self.label_36.setPixmap(QPixmap(u"../Sources/Images/heli.png"))
        self.label_36.setScaledContents(True)
        self.label_37 = QLabel(self.page_5)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(580, 100, 121, 161))
        self.label_37.setPixmap(QPixmap(u"../Sources/Images/mu\u00f1eca.png"))
        self.label_37.setScaledContents(True)
        self.label_38 = QLabel(self.page_5)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(70, 190, 121, 71))
        self.label_38.setPixmap(QPixmap(u"../Sources/Images/camion.png"))
        self.label_38.setScaledContents(True)
        self.label_39 = QLabel(self.page_5)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(480, 130, 91, 131))
        self.label_39.setPixmap(QPixmap(u"../Sources/Images/robot.png"))
        self.label_39.setScaledContents(True)
        self.label_40 = QLabel(self.page_5)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(70, 280, 641, 101))
        self.label_40.setFont(font1)
        self.label_40.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnTerminado = QPushButton(self.page_5)
        self.btnTerminado.setObjectName(u"btnTerminado")
        self.btnTerminado.setGeometry(QRect(290, 400, 211, 71))
        font2 = QFont()
        font2.setPointSize(22)
        font2.setBold(True)
        self.btnTerminado.setFont(font2)
        self.btnTerminado.setStyleSheet(u"background-color:rgb(164, 12, 184)")
        StackedWidget.addWidget(self.page_5)

        self.retranslateUi(StackedWidget)

        StackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(StackedWidget)
    # setupUi

    def retranslateUi(self, StackedWidget):
        StackedWidget.setWindowTitle(QCoreApplication.translate("StackedWidget", u"StackedWidget", None))
        self.label.setText(QCoreApplication.translate("StackedWidget", u"QUICKSORT", None))
        self.label_2.setText(QCoreApplication.translate("StackedWidget", u"Imagina que tienes un mont\u00f3n de juguetes de diferentes tama\u00f1os y \n"
"quieres ordenarlos del m\u00e1s peque\u00f1o al m\u00e1s grande. \n"
"\u00a1Hacerlo puede ser muy r\u00e1pido y divertido si usas un m\u00e9todo llamado \"Quicksort\"!\n"
"Pensemos que tus juguetes son n\u00fameros. Digamos que tienes estos", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.label_7.setText("")
        self.label_8.setText(QCoreApplication.translate("StackedWidget", u"[            5            ,           1           ,             3            ,           2            ,             4             ]", None))
        self.btnNext.setText(QCoreApplication.translate("StackedWidget", u"Siguiente", None))
        self.label_9.setText(QCoreApplication.translate("StackedWidget", u"QUICKSORT", None))
        self.label_10.setText(QCoreApplication.translate("StackedWidget", u"Primero, escoge un juguete cualquiera del mont\u00f3n para que sea tu \"pivote\". \n"
"No importa cu\u00e1l elijas, \u00a1cualquiera funciona!\n"
"En este caso, escogeremos el de en medio, \u00a1El numero 3!", None))
        self.label_11.setText("")
        self.label_12.setText(QCoreApplication.translate("StackedWidget", u"Ahora, lo que haremos es preguntar:\n"
" \u00bfLos demas juguetes son mas grandes o peque\u00f1os que el helic\u00f3ptero?\n"
"Si son mas grandes, se iran a la derecha, si son mas peque\u00f1os, a la izquierda.", None))
        self.btnNext_2.setText(QCoreApplication.translate("StackedWidget", u"Siguiente", None))
        self.label_13.setText(QCoreApplication.translate("StackedWidget", u"QUICKSORT", None))
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_18.setText("")
        self.label_19.setText("")
        self.label_20.setText("")
        self.label_21.setText("")
        self.label_22.setText(QCoreApplication.translate("StackedWidget", u"\u00bfEs mas grande o peque\u00f1a la mu\u00f1eca? \n"
"Mas grande, se va a la derecha.", None))
        self.label_23.setText(QCoreApplication.translate("StackedWidget", u"\u00bfEs mas grande o peque\u00f1a la el carro? \n"
"Mas peque\u00f1o, se va a la izquierda.", None))
        self.label_24.setText(QCoreApplication.translate("StackedWidget", u"\u00bfEs mas grande o peque\u00f1o el camion? \n"
"Mas peque\u00f1o, se va a la izquierda.", None))
        self.label_25.setText(QCoreApplication.translate("StackedWidget", u"\u00bfEs mas grande o peque\u00f1o el robot? \n"
"Mas grande, se va a la derecha.", None))
        self.btnNext_3.setText(QCoreApplication.translate("StackedWidget", u"Siguiente", None))
        self.label_26.setText(QCoreApplication.translate("StackedWidget", u"QUICKSORT", None))
        self.label_27.setText("")
        self.label_28.setText("")
        self.label_29.setText("")
        self.label_30.setText("")
        self.label_31.setText("")
        self.label_32.setText(QCoreApplication.translate("StackedWidget", u"Despues de esa primera comparaci\u00f3n, nos queda algo asi, pero no esta ordenado, \n"
"vemos que la mu\u00f1eca es mas grande que el robot, deber\u00eda ir al ultimo.\n"
"Debemos hacer lo mismo que al principio, de los jueguetes que estan a la derecha del \n"
"helic\u00f3ptero, escogemos uno para hacer la comparaci\u00f3n.", None))
        self.label_33.setText(QCoreApplication.translate("StackedWidget", u"En este caso, vamos a comparar al robot y nos preguntamos\n"
" \u00bfLa mu\u00f1eca es mas peque\u00f1a o grande que el robot?\n"
" Es mas grande que el robot, entonces se mueve a la derecha.", None))
        self.btnNext_4.setText(QCoreApplication.translate("StackedWidget", u"Siguiente", None))
        self.label_34.setText(QCoreApplication.translate("StackedWidget", u"QUICKSORT", None))
        self.label_35.setText("")
        self.label_36.setText("")
        self.label_37.setText("")
        self.label_38.setText("")
        self.label_39.setText("")
        self.label_40.setText(QCoreApplication.translate("StackedWidget", u"Y LISTO; YA HEMOS TERMINADO DE ORDENAR LOS JUGUETES!!!\n"
"Te gust\u00f3?", None))
        self.btnTerminado.setText(QCoreApplication.translate("StackedWidget", u"TERMINADO", None))
    # retranslateUi

