# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'strassen.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_StrassenVista(object):
    def setupUi(self, StrassenVista):
        if not StrassenVista.objectName():
            StrassenVista.setObjectName(u"StrassenVista")
        StrassenVista.resize(724, 469)
        StrassenVista.setStyleSheet(u"background-color: rgb(43, 136, 74)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(150, 20, 441, 41))
        font = QFont()
        font.setFamilies([u"Caprasimo"])
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: white; background-color:transparent")
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(100, 80, 521, 141))
        font1 = QFont()
        font1.setFamilies([u"Caprasimo"])
        font1.setPointSize(12)
        font1.setBold(False)
        self.label_2.setFont(font1)
        self.label_2.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(130, 230, 271, 201))
        font2 = QFont()
        font2.setFamilies([u"Caprasimo"])
        font2.setPointSize(17)
        font2.setBold(True)
        font2.setItalic(False)
        self.label_3.setFont(font2)
        self.label_3.setStyleSheet(u"color: white; font: bold; font-size: 17pt")
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.btnNext = QPushButton(self.page)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(630, 420, 75, 24))
        self.btnNext.setStyleSheet(u"background-color: grey")
        self.label_52 = QLabel(self.page)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(150, 20, 451, 41))
        self.label_52.setFont(font)
        self.label_52.setStyleSheet(u"color: black; background-color:transparent")
        self.label_52.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_57 = QLabel(self.page)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(410, 240, 151, 191))
        self.label_57.setPixmap(QPixmap(u"Sources/Images/strass.png"))
        self.label_57.setScaledContents(True)
        StrassenVista.addWidget(self.page)
        self.label_52.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.btnNext.raise_()
        self.label_57.raise_()
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(100, 90, 521, 41))
        font3 = QFont()
        font3.setFamilies([u"Caprasimo"])
        font3.setPointSize(12)
        self.label_5.setFont(font3)
        self.label_5.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(120, 180, 71, 71))
        self.label_6.setPixmap(QPixmap(u"Sources/Images/ninio1.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(210, 180, 71, 71))
        self.label_7.setPixmap(QPixmap(u"Sources/Images/ninio2.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setWordWrap(False)
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(120, 270, 71, 71))
        self.label_8.setPixmap(QPixmap(u"Sources/Images/ninio3.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setWordWrap(False)
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(210, 270, 71, 71))
        self.label_9.setPixmap(QPixmap(u"Sources/Images/ninio4.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setWordWrap(False)
        self.label_10 = QLabel(self.page_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(560, 180, 71, 71))
        self.label_10.setPixmap(QPixmap(u"Sources/Images/ninio4.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setWordWrap(False)
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(470, 270, 71, 71))
        self.label_11.setPixmap(QPixmap(u"Sources/Images/ninio1.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setWordWrap(False)
        self.label_12 = QLabel(self.page_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(470, 180, 71, 71))
        self.label_12.setPixmap(QPixmap(u"Sources/Images/ninio2.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setWordWrap(False)
        self.label_13 = QLabel(self.page_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(560, 270, 71, 71))
        self.label_13.setPixmap(QPixmap(u"Sources/Images/ninio3.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setWordWrap(False)
        self.label_14 = QLabel(self.page_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(130, 350, 121, 41))
        font4 = QFont()
        font4.setFamilies([u"Caprasimo"])
        font4.setPointSize(19)
        font4.setBold(True)
        font4.setItalic(False)
        self.label_14.setFont(font4)
        self.label_14.setStyleSheet(u"color: white; font: bold; font-size: 19pt")
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_15 = QLabel(self.page_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(490, 350, 121, 41))
        self.label_15.setFont(font4)
        self.label_15.setStyleSheet(u"color: white; font: bold; font-size: 19pt")
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_18 = QLabel(self.page_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 200, 61, 31))
        self.label_18.setFont(font4)
        self.label_18.setStyleSheet(u"color: white; font: bold; font-size: 19pt")
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_19 = QLabel(self.page_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(290, 200, 61, 31))
        self.label_19.setFont(font4)
        self.label_19.setStyleSheet(u"color: white; font: bold; font-size: 19pt")
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_20 = QLabel(self.page_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 290, 61, 31))
        self.label_20.setFont(font4)
        self.label_20.setStyleSheet(u"color: white; font: bold; font-size: 19pt")
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_21 = QLabel(self.page_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(290, 290, 61, 31))
        self.label_21.setFont(font4)
        self.label_21.setStyleSheet(u"color: white; font: bold; font-size: 19pt")
        self.label_21.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_22 = QLabel(self.page_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(400, 200, 61, 31))
        self.label_22.setFont(font4)
        self.label_22.setStyleSheet(u"color: white; font: bold; font-size: 19pt")
        self.label_22.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_23 = QLabel(self.page_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(400, 290, 61, 31))
        self.label_23.setFont(font4)
        self.label_23.setStyleSheet(u"color: white; font: bold; font-size: 19pt")
        self.label_23.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_24 = QLabel(self.page_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(640, 200, 61, 31))
        self.label_24.setFont(font4)
        self.label_24.setStyleSheet(u"color: white; font: bold; font-size: 19pt")
        self.label_24.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_25 = QLabel(self.page_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(640, 290, 61, 31))
        self.label_25.setFont(font4)
        self.label_25.setStyleSheet(u"color: white; font: bold; font-size: 19pt")
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_2 = QPushButton(self.page_2)
        self.btnNext_2.setObjectName(u"btnNext_2")
        self.btnNext_2.setGeometry(QRect(630, 420, 75, 24))
        self.btnNext_2.setStyleSheet(u"background-color: grey")
        self.label_53 = QLabel(self.page_2)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(150, 20, 451, 41))
        self.label_53.setFont(font)
        self.label_53.setStyleSheet(u"color: black; background-color:transparent")
        self.label_53.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4 = QLabel(self.page_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 20, 441, 41))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color: white; background-color:transparent")
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StrassenVista.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(100, 70, 521, 51))
        self.label_16.setFont(font3)
        self.label_16.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_16.setWordWrap(True)
        self.label_26 = QLabel(self.page_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(100, 140, 521, 31))
        self.label_26.setFont(font3)
        self.label_26.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_26.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_26.setWordWrap(True)
        self.label_27 = QLabel(self.page_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(100, 180, 521, 41))
        self.label_27.setFont(font3)
        self.label_27.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_27.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_27.setWordWrap(True)
        self.label_28 = QLabel(self.page_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(70, 250, 251, 21))
        self.label_28.setFont(font3)
        self.label_28.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_28.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_29 = QLabel(self.page_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(70, 300, 261, 21))
        self.label_29.setFont(font3)
        self.label_29.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_30 = QLabel(self.page_3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(380, 250, 241, 21))
        self.label_30.setFont(font3)
        self.label_30.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_30.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_31 = QLabel(self.page_3)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(380, 300, 241, 21))
        self.label_31.setFont(font3)
        self.label_31.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_31.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_32 = QLabel(self.page_3)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(180, 350, 351, 21))
        self.label_32.setFont(font3)
        self.label_32.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_32.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_32.setWordWrap(True)
        self.label_33 = QLabel(self.page_3)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(100, 390, 521, 51))
        self.label_33.setFont(font3)
        self.label_33.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_33.setWordWrap(True)
        self.btnNext_3 = QPushButton(self.page_3)
        self.btnNext_3.setObjectName(u"btnNext_3")
        self.btnNext_3.setGeometry(QRect(630, 420, 75, 24))
        self.btnNext_3.setStyleSheet(u"background-color: grey")
        self.label_54 = QLabel(self.page_3)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(150, 20, 451, 41))
        self.label_54.setFont(font)
        self.label_54.setStyleSheet(u"color: black; background-color:transparent")
        self.label_54.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_17 = QLabel(self.page_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(150, 20, 441, 41))
        self.label_17.setFont(font)
        self.label_17.setStyleSheet(u"color: white; background-color:transparent")
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StrassenVista.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_35 = QLabel(self.page_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(120, 90, 491, 71))
        self.label_35.setFont(font3)
        self.label_35.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_35.setWordWrap(True)
        self.label_36 = QLabel(self.page_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(150, 170, 441, 31))
        self.label_36.setFont(font3)
        self.label_36.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_36.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_36.setWordWrap(True)
        self.label_37 = QLabel(self.page_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(300, 210, 111, 31))
        self.label_37.setFont(font4)
        self.label_37.setStyleSheet(u"color: black; font: bold; font-size: 19pt")
        self.label_38 = QLabel(self.page_4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(220, 260, 271, 21))
        self.label_38.setFont(font3)
        self.label_38.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_38.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_39 = QLabel(self.page_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(90, 300, 251, 21))
        self.label_39.setFont(font3)
        self.label_39.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_39.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_40 = QLabel(self.page_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(90, 360, 251, 21))
        self.label_40.setFont(font3)
        self.label_40.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_40.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_41 = QLabel(self.page_4)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(390, 300, 271, 21))
        self.label_41.setFont(font3)
        self.label_41.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_41.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_42 = QLabel(self.page_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(90, 330, 251, 21))
        self.label_42.setFont(font3)
        self.label_42.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_42.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_44 = QLabel(self.page_4)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(390, 360, 271, 21))
        self.label_44.setFont(font3)
        self.label_44.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_44.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_45 = QLabel(self.page_4)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(390, 330, 271, 21))
        self.label_45.setFont(font3)
        self.label_45.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_45.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnNext_4 = QPushButton(self.page_4)
        self.btnNext_4.setObjectName(u"btnNext_4")
        self.btnNext_4.setGeometry(QRect(630, 420, 75, 24))
        self.btnNext_4.setStyleSheet(u"background-color: grey")
        self.label_55 = QLabel(self.page_4)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(150, 20, 451, 41))
        self.label_55.setFont(font)
        self.label_55.setStyleSheet(u"color: black; background-color:transparent")
        self.label_55.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_34 = QLabel(self.page_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(150, 20, 441, 41))
        self.label_34.setFont(font)
        self.label_34.setStyleSheet(u"color: white; background-color:transparent")
        self.label_34.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StrassenVista.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.label_43 = QLabel(self.page_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(110, 60, 521, 71))
        self.label_43.setFont(font3)
        self.label_43.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_43.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_43.setWordWrap(True)
        self.label_47 = QLabel(self.page_5)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(160, 150, 221, 21))
        self.label_47.setFont(font3)
        self.label_47.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_47.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_48 = QLabel(self.page_5)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(360, 150, 271, 21))
        self.label_48.setFont(font3)
        self.label_48.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_48.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_49 = QLabel(self.page_5)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(130, 200, 271, 21))
        self.label_49.setFont(font3)
        self.label_49.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_49.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_50 = QLabel(self.page_5)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(360, 200, 271, 21))
        self.label_50.setFont(font3)
        self.label_50.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_50.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_51 = QLabel(self.page_5)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(110, 260, 521, 71))
        self.label_51.setFont(font3)
        self.label_51.setStyleSheet(u"color: white; font-size: 12pt")
        self.label_51.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_51.setWordWrap(True)
        self.btnTerminar = QPushButton(self.page_5)
        self.btnTerminar.setObjectName(u"btnTerminar")
        self.btnTerminar.setGeometry(QRect(280, 360, 181, 71))
        font5 = QFont()
        font5.setFamilies([u"Caprasimo"])
        font5.setPointSize(12)
        font5.setBold(True)
        font5.setItalic(False)
        self.btnTerminar.setFont(font5)
        self.btnTerminar.setStyleSheet(u"background-color: grey; font-size: 12pt; font: bold;")
        self.label_56 = QLabel(self.page_5)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(150, 20, 451, 41))
        self.label_56.setFont(font)
        self.label_56.setStyleSheet(u"color: black; background-color:transparent")
        self.label_56.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_46 = QLabel(self.page_5)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(150, 20, 441, 41))
        self.label_46.setFont(font)
        self.label_46.setStyleSheet(u"color: white; background-color:transparent")
        self.label_46.setAlignment(Qt.AlignmentFlag.AlignCenter)
        StrassenVista.addWidget(self.page_5)

        self.retranslateUi(StrassenVista)

        StrassenVista.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(StrassenVista)
    # setupUi

    def retranslateUi(self, StrassenVista):
        StrassenVista.setWindowTitle(QCoreApplication.translate("StrassenVista", u"StackedWidget", None))
        self.label.setText(QCoreApplication.translate("StrassenVista", u"Metodo de Strassen ", None))
        self.label_2.setText(QCoreApplication.translate("StrassenVista", u"El m\u00e9todo de Strassen es una forma m\u00e1s r\u00e1pida y astuta de multiplicar matrices, que son como tablas con n\u00fameros organizados en filas y columnas.\n"
"\n"
"Se llama as\u00ed porque fue inventado por un matem\u00e1tico alem\u00e1n llamado Volker Strassen en 1969, quien se dio cuenta de algo curioso:", None))
        self.label_3.setText(QCoreApplication.translate("StrassenVista", u"\u201c\u00a1No necesitamos hacer tantas multiplicaciones como pens\u00e1bamos para resolver una multiplicaci\u00f3n de matrices!\u201d", None))
        self.btnNext.setText(QCoreApplication.translate("StrassenVista", u"SIGUIENTE", None))
        self.label_52.setText(QCoreApplication.translate("StrassenVista", u"Metodo de Strassen ", None))
        self.label_57.setText("")
        self.label_5.setText(QCoreApplication.translate("StrassenVista", u"Tenemos dos equipos de amigos: el equipo A y el equipo B. Cada equipo tiene 2 ni\u00f1os en 2 filas", None))
        self.label_6.setText("")
        self.label_7.setText("")
        self.label_8.setText("")
        self.label_9.setText("")
        self.label_10.setText("")
        self.label_11.setText("")
        self.label_12.setText("")
        self.label_13.setText("")
        self.label_14.setText(QCoreApplication.translate("StrassenVista", u"Equipo A", None))
        self.label_15.setText(QCoreApplication.translate("StrassenVista", u"Equipo B", None))
        self.label_18.setText(QCoreApplication.translate("StrassenVista", u"A1,1", None))
        self.label_19.setText(QCoreApplication.translate("StrassenVista", u"A1,2", None))
        self.label_20.setText(QCoreApplication.translate("StrassenVista", u"A2,1", None))
        self.label_21.setText(QCoreApplication.translate("StrassenVista", u"A2,2", None))
        self.label_22.setText(QCoreApplication.translate("StrassenVista", u"B1,1", None))
        self.label_23.setText(QCoreApplication.translate("StrassenVista", u"B2,1", None))
        self.label_24.setText(QCoreApplication.translate("StrassenVista", u"B1,2", None))
        self.label_25.setText(QCoreApplication.translate("StrassenVista", u"B2,2", None))
        self.btnNext_2.setText(QCoreApplication.translate("StrassenVista", u"SIGUIENTE", None))
        self.label_53.setText(QCoreApplication.translate("StrassenVista", u"Metodo de Strassen ", None))
        self.label_4.setText(QCoreApplication.translate("StrassenVista", u"Metodo de Strassen ", None))
        self.label_16.setText(QCoreApplication.translate("StrassenVista", u"Queremos ver cu\u00e1ntos dulces puede compartir cada ni\u00f1o del equipo A con cada ni\u00f1o del equipo B. Pero no vamos a contar de uno en uno. Vamos a usar matem\u00e1ticas para hacerlo m\u00e1s f\u00e1cil", None))
        self.label_26.setText(QCoreApplication.translate("StrassenVista", u"Cada chico esta etiquetado segun su posicion en la fila y columna", None))
        self.label_27.setText(QCoreApplication.translate("StrassenVista", u"Si hicieramos el metodo simple, el de siempre tendriamos que hacer lo siguiente", None))
        self.label_28.setText(QCoreApplication.translate("StrassenVista", u"C1 = A1,1 * B1,1 + A1,2 * B2,1", None))
        self.label_29.setText(QCoreApplication.translate("StrassenVista", u"C2 = A1,1 * B1,2 + A1,2 * B2,2", None))
        self.label_30.setText(QCoreApplication.translate("StrassenVista", u"C3 = A2,1* B1,1 + A2,2 + B2,1", None))
        self.label_31.setText(QCoreApplication.translate("StrassenVista", u"C4 = A2,1 * B1,2 + A2,2 * B2,2", None))
        self.label_32.setText(QCoreApplication.translate("StrassenVista", u"Las C's representan nuestros resultados", None))
        self.label_33.setText(QCoreApplication.translate("StrassenVista", u"De esta forma nos tardariamos mucho y si tenemos mas ni\u00f1os, tendriamos que hacer mas cuentas, lo que lo hace lento y muy tedioso", None))
        self.btnNext_3.setText(QCoreApplication.translate("StrassenVista", u"SIGUIENTE", None))
        self.label_54.setText(QCoreApplication.translate("StrassenVista", u"Metodo de Strassen ", None))
        self.label_17.setText(QCoreApplication.translate("StrassenVista", u"Metodo de Strassen ", None))
        self.label_35.setText(QCoreApplication.translate("StrassenVista", u"El metodo de Strassen consiste en en vez de hacer todas esas cuentas, hagamos una menos, que aunque no parezca gran diferencia, en este metodo solo haremos sumas y restas", None))
        self.label_36.setText(QCoreApplication.translate("StrassenVista", u"Compartiremos nuestros dulces de la siguiente forma", None))
        self.label_37.setText(QCoreApplication.translate("StrassenVista", u"Equipos", None))
        self.label_38.setText(QCoreApplication.translate("StrassenVista", u"M1 = (A1,1 + A2,2) * (B1,1 + B2,2)", None))
        self.label_39.setText(QCoreApplication.translate("StrassenVista", u"M2 = (A2,1 + A2,2) * (B1,1)", None))
        self.label_40.setText(QCoreApplication.translate("StrassenVista", u"M4 =A2,2 * (B2,1 - B1,1)", None))
        self.label_41.setText(QCoreApplication.translate("StrassenVista", u"M5 = (A1,1 + A1,2) * (B1,1 + B1,2)", None))
        self.label_42.setText(QCoreApplication.translate("StrassenVista", u"M3 = A1,1 * (B1,2 - B2,2)", None))
        self.label_44.setText(QCoreApplication.translate("StrassenVista", u"M7 = (A1,2 - A2,2) * (B2,1 + B2,2)", None))
        self.label_45.setText(QCoreApplication.translate("StrassenVista", u"M6 = (A2,1 - A1,1) * (B1,1 + B1,2)", None))
        self.btnNext_4.setText(QCoreApplication.translate("StrassenVista", u"SIGUIENTE", None))
        self.label_55.setText(QCoreApplication.translate("StrassenVista", u"Metodo de Strassen ", None))
        self.label_34.setText(QCoreApplication.translate("StrassenVista", u"Metodo de Strassen ", None))
        self.label_43.setText(QCoreApplication.translate("StrassenVista", u"Ahora, con estos resultados formaremos nuestra tabla que nos dara el resultado de como repartimos nuestros dulces", None))
        self.label_47.setText(QCoreApplication.translate("StrassenVista", u"C1,1 = M1+M4 - M5 + M7", None))
        self.label_48.setText(QCoreApplication.translate("StrassenVista", u"C1,2 = M3 + M5", None))
        self.label_49.setText(QCoreApplication.translate("StrassenVista", u"C2,1 = M2 + M4", None))
        self.label_50.setText(QCoreApplication.translate("StrassenVista", u"C2,2 = M1 -M2 +M3 +M6", None))
        self.label_51.setText(QCoreApplication.translate("StrassenVista", u"Esto nos da el resultado de los dulces que cada ni\u00f1o puede compartir de una manera mucho mas entendible e incluso organizada", None))
        self.btnTerminar.setText(QCoreApplication.translate("StrassenVista", u"TERMINADO", None))
        self.label_56.setText(QCoreApplication.translate("StrassenVista", u"Metodo de Strassen ", None))
        self.label_46.setText(QCoreApplication.translate("StrassenVista", u"Metodo de Strassen ", None))
    # retranslateUi

