# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tablasHash.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        if not StackedWidget.objectName():
            StackedWidget.setObjectName(u"StackedWidget")
        StackedWidget.resize(764, 502)
        StackedWidget.setStyleSheet(u"background-color:rgb(255, 200, 124)")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(280, 20, 181, 41))
        self.label.setStyleSheet(u"FONT-SIZE: 18PT; font:bold; color: balck")
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(120, 60, 511, 131))
        self.label_2.setStyleSheet(u"color:black; font-size: 12pt")
        self.label_2.setWordWrap(True)
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(120, 220, 541, 131))
        self.label_3.setStyleSheet(u"color:black; font-size: 12pt")
        self.label_3.setWordWrap(True)
        self.btnNext = QPushButton(self.page)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(630, 450, 75, 24))
        self.btnNext.setStyleSheet(u"background-color: rgb(0,0,0)")
        StackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_4 = QLabel(self.page_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(270, 0, 181, 41))
        self.label_4.setStyleSheet(u"FONT-SIZE: 18PT; font:bold; color: balck")
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 30, 691, 81))
        self.label_5.setStyleSheet(u"color:black; font-size: 12pt")
        self.label_5.setWordWrap(True)
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 90, 711, 81))
        self.label_6.setStyleSheet(u"color:black; font-size: 12pt")
        self.label_6.setWordWrap(True)
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 160, 701, 81))
        self.label_7.setStyleSheet(u"color:black; font-size: 12pt")
        self.label_7.setWordWrap(True)
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(60, 260, 641, 71))
        self.label_8.setStyleSheet(u"color:black; font-size: 12pt")
        self.label_8.setWordWrap(True)
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 240, 501, 21))
        self.label_9.setStyleSheet(u"color:black; font-size: 12pt; font:bold")
        self.label_10 = QLabel(self.page_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 330, 761, 131))
        self.label_10.setStyleSheet(u"color:black; font-size: 12pt")
        self.label_10.setWordWrap(True)
        self.btnNext_2 = QPushButton(self.page_2)
        self.btnNext_2.setObjectName(u"btnNext_2")
        self.btnNext_2.setGeometry(QRect(660, 450, 75, 24))
        self.btnNext_2.setStyleSheet(u"background-color: rgb(0,0,0)")
        StackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_11 = QLabel(self.page_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(260, 10, 181, 41))
        self.label_11.setStyleSheet(u"FONT-SIZE: 18PT; font:bold; color: balck")
        self.label_12 = QLabel(self.page_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(70, 70, 241, 281))
        self.label_12.setPixmap(QPixmap(u"Sources/Images/estanteria.png"))
        self.label_12.setScaledContents(True)
        self.label_13 = QLabel(self.page_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(390, 110, 81, 81))
        self.label_13.setPixmap(QPixmap(u"Sources/Images/carro.png"))
        self.label_13.setScaledContents(True)
        self.label_14 = QLabel(self.page_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(500, 220, 101, 121))
        self.label_14.setPixmap(QPixmap(u"Sources/Images/robot.png"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.page_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(560, 110, 111, 81))
        self.label_15.setPixmap(QPixmap(u"Sources/Images/osito.png"))
        self.label_15.setScaledContents(True)
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(350, 230, 111, 101))
        self.label_16.setPixmap(QPixmap(u"Sources/Images/nintendo.png"))
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.page_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(620, 220, 111, 121))
        self.label_17.setPixmap(QPixmap(u"Sources/Images/max.png"))
        self.label_17.setScaledContents(True)
        self.label_18 = QLabel(self.page_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(160, 400, 471, 41))
        self.label_18.setStyleSheet(u"color: black; font-size:12pt")
        self.label_18.setWordWrap(True)
        self.btnNext_3 = QPushButton(self.page_3)
        self.btnNext_3.setObjectName(u"btnNext_3")
        self.btnNext_3.setGeometry(QRect(660, 460, 75, 24))
        self.btnNext_3.setStyleSheet(u"background-color: rgb(0,0,0)")
        StackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_21 = QLabel(self.page_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 70, 471, 41))
        self.label_21.setStyleSheet(u"color: black; font-size:12pt")
        self.label_21.setWordWrap(True)
        self.label_23 = QLabel(self.page_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(270, 20, 181, 41))
        self.label_23.setStyleSheet(u"FONT-SIZE: 18PT; font:bold; color: balck")
        self.label_26 = QLabel(self.page_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(910, 440, 111, 121))
        self.label_26.setPixmap(QPixmap(u"Sources/Images/max.png"))
        self.label_26.setScaledContents(True)
        self.label_19 = QLabel(self.page_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(40, 130, 241, 281))
        self.label_19.setPixmap(QPixmap(u"Sources/Images/estanteria.png"))
        self.label_19.setScaledContents(True)
        self.label_20 = QLabel(self.page_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(150, 170, 81, 81))
        self.label_20.setPixmap(QPixmap(u"Sources/Images/carro.png"))
        self.label_20.setScaledContents(True)
        self.label_22 = QLabel(self.page_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(300, 140, 101, 91))
        self.label_22.setStyleSheet(u"font-size:12pt; color:black; font:bold")
        self.label_22.setWordWrap(True)
        self.label_24 = QLabel(self.page_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(150, 280, 71, 81))
        self.label_24.setPixmap(QPixmap(u"Sources/Images/robot.png"))
        self.label_24.setScaledContents(True)
        self.label_25 = QLabel(self.page_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(300, 270, 101, 91))
        self.label_25.setStyleSheet(u"font-size:12pt; color:black; font:bold")
        self.label_25.setWordWrap(True)
        self.label_27 = QLabel(self.page_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(540, 60, 171, 41))
        self.label_27.setStyleSheet(u"color: black; font-size:12pt; font: bold")
        self.label_27.setWordWrap(True)
        self.label_28 = QLabel(self.page_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(470, 120, 111, 121))
        self.label_28.setPixmap(QPixmap(u"Sources/Images/max.png"))
        self.label_28.setScaledContents(True)
        self.label_29 = QLabel(self.page_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(470, 250, 111, 81))
        self.label_29.setPixmap(QPixmap(u"Sources/Images/osito.png"))
        self.label_29.setScaledContents(True)
        self.label_30 = QLabel(self.page_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(470, 350, 111, 101))
        self.label_30.setPixmap(QPixmap(u"Sources/Images/nintendo.png"))
        self.label_30.setScaledContents(True)
        self.label_31 = QLabel(self.page_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(590, 140, 101, 91))
        self.label_31.setStyleSheet(u"font-size:12pt; color:black; font:bold")
        self.label_31.setWordWrap(True)
        self.label_32 = QLabel(self.page_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(590, 240, 101, 91))
        self.label_32.setStyleSheet(u"font-size:12pt; color:black; font:bold")
        self.label_32.setWordWrap(True)
        self.label_33 = QLabel(self.page_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(590, 360, 101, 91))
        self.label_33.setStyleSheet(u"font-size:12pt; color:black; font:bold")
        self.label_33.setWordWrap(True)
        self.btnNext_4 = QPushButton(self.page_4)
        self.btnNext_4.setObjectName(u"btnNext_4")
        self.btnNext_4.setGeometry(QRect(670, 450, 75, 24))
        self.btnNext_4.setStyleSheet(u"background-color: rgb(0,0,0)")
        StackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.label_37 = QLabel(self.page_5)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(50, 70, 471, 41))
        self.label_37.setStyleSheet(u"color: black; font-size:12pt")
        self.label_37.setWordWrap(True)
        self.label_38 = QLabel(self.page_5)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(420, 360, 101, 31))
        self.label_38.setStyleSheet(u"font-size:12pt; color:black; font:bold")
        self.label_38.setWordWrap(True)
        self.label_39 = QLabel(self.page_5)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(410, 210, 111, 101))
        self.label_39.setPixmap(QPixmap(u"Sources/Images/nintendo.png"))
        self.label_39.setScaledContents(True)
        self.label_40 = QLabel(self.page_5)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(620, 150, 111, 121))
        self.label_40.setPixmap(QPixmap(u"Sources/Images/max.png"))
        self.label_40.setScaledContents(True)
        self.label_41 = QLabel(self.page_5)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(590, 360, 101, 31))
        self.label_41.setStyleSheet(u"font-size:12pt; color:black; font:bold")
        self.label_41.setWordWrap(True)
        self.label_42 = QLabel(self.page_5)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(290, 20, 181, 41))
        self.label_42.setStyleSheet(u"FONT-SIZE: 18PT; font:bold; color: balck")
        self.label_44 = QLabel(self.page_5)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(220, 350, 101, 41))
        self.label_44.setStyleSheet(u"font-size:12pt; color:black; font:bold")
        self.label_44.setWordWrap(True)
        self.label_47 = QLabel(self.page_5)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(60, 360, 101, 21))
        self.label_47.setStyleSheet(u"font-size:12pt; color:black; font:bold")
        self.label_47.setWordWrap(True)
        self.label_48 = QLabel(self.page_5)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(600, 220, 71, 81))
        self.label_48.setPixmap(QPixmap(u"Sources/Images/robot.png"))
        self.label_48.setScaledContents(True)
        self.label_45 = QLabel(self.page_5)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(400, 270, 131, 91))
        self.label_45.setPixmap(QPixmap(u"Sources/Images/caja.png"))
        self.label_45.setScaledContents(True)
        self.label_46 = QLabel(self.page_5)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(580, 270, 131, 91))
        self.label_46.setPixmap(QPixmap(u"Sources/Images/caja.png"))
        self.label_46.setScaledContents(True)
        self.label_36 = QLabel(self.page_5)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(50, 220, 81, 81))
        self.label_36.setPixmap(QPixmap(u"Sources/Images/carro.png"))
        self.label_36.setScaledContents(True)
        self.label_43 = QLabel(self.page_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(220, 230, 111, 81))
        self.label_43.setPixmap(QPixmap(u"Sources/Images/osito.png"))
        self.label_43.setScaledContents(True)
        self.label_35 = QLabel(self.page_5)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(210, 270, 131, 91))
        self.label_35.setPixmap(QPixmap(u"Sources/Images/caja.png"))
        self.label_35.setScaledContents(True)
        self.label_49 = QLabel(self.page_5)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(30, 260, 131, 91))
        self.label_49.setPixmap(QPixmap(u"Sources/Images/caja.png"))
        self.label_49.setScaledContents(True)
        self.label_50 = QLabel(self.page_5)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(40, 120, 601, 61))
        self.label_50.setStyleSheet(u"color: black; font-size:12pt")
        self.label_50.setWordWrap(True)
        self.btnTerminar = QPushButton(self.page_5)
        self.btnTerminar.setObjectName(u"btnTerminar")
        self.btnTerminar.setGeometry(QRect(660, 440, 75, 24))
        self.btnTerminar.setStyleSheet(u"background-color: rgb(0,0,0)")
        StackedWidget.addWidget(self.page_5)

        self.retranslateUi(StackedWidget)

        StackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(StackedWidget)
    # setupUi

    def retranslateUi(self, StackedWidget):
        StackedWidget.setWindowTitle(QCoreApplication.translate("StackedWidget", u"StackedWidget", None))
        self.label.setText(QCoreApplication.translate("StackedWidget", u"TABLAS HASH", None))
        self.label_2.setText(QCoreApplication.translate("StackedWidget", u"Imagina que tienes much\u00edsimos datos y quieres encontrar uno espec\u00edfico de inmediato. Las tablas hash logran esto usando un truco inteligente: toman la clave (lo que usas para buscar, como un nombre o un ID) y, a trav\u00e9s de una funci\u00f3n hash, la convierten en una direcci\u00f3n \u00fanica donde guardar\u00e1n el valor asociado.", None))
        self.label_3.setText(QCoreApplication.translate("StackedWidget", u"Pero para facilitar el entendimiento imagina la Estanter\u00eda M\u00e1gica de Juguetes!\n"
"Imagina que tienes una estanter\u00eda de juguetes s\u00faper especial y m\u00e1gica. En lugar de buscar juguete por juguete hasta encontrar el que quieres, esta estanter\u00eda tiene un truco", None))
        self.btnNext.setText(QCoreApplication.translate("StackedWidget", u"Siguiente", None))
        self.label_4.setText(QCoreApplication.translate("StackedWidget", u"TABLAS HASH", None))
        self.label_5.setText(QCoreApplication.translate("StackedWidget", u"1.- Cada juguete tiene una etiqueta m\u00e1gica: Cuando quieres guardar un juguete (por ejemplo, tu coche rojo), la estanter\u00eda le pone una etiqueta m\u00e1gica.", None))
        self.label_6.setText(QCoreApplication.translate("StackedWidget", u"2.-La etiqueta te dice d\u00f3nde guardarlo: Esa etiqueta te dice exactamente en qu\u00e9 caja de la estanter\u00eda debes poner el coche rojo. \u00a1Es como un n\u00famero de caja secreta! As\u00ed, el coche rojo siempre va a la caja n\u00famero 3.", None))
        self.label_7.setText(QCoreApplication.translate("StackedWidget", u"3.-Para encontrarlo, usas la etiqueta: Si luego quieres jugar con tu coche rojo, \u00a1no tienes que buscar en todas las cajas! Solo miras su etiqueta m\u00e1gica, que te dice \"caja n\u00famero 3\", y vas directo a esa caja para sacarlo. \u00a1Es s\u00faper r\u00e1pido!", None))
        self.label_8.setText(QCoreApplication.translate("StackedWidget", u"Ah, esa es la parte divertida! A veces, la etiqueta m\u00e1gica de tu coche rojo dice \"caja 3\", y la etiqueta m\u00e1gica de tu osito de peluche tambi\u00e9n dice \"caja 3\". \u00a1Ups! Eso es un embotellamiento (una colisi\u00f3n). Para arreglar usamos:", None))
        self.label_9.setText(QCoreApplication.translate("StackedWidget", u"\u00bfY qu\u00e9 pasa si hay dos juguetes que quieren ir a la misma caja?", None))
        self.label_10.setText(QCoreApplication.translate("StackedWidget", u"Cajones secretos dentro de cada caja: Dentro de la caja n\u00famero 3, en lugar de un solo juguete, hay como peque\u00f1os cajones secretos. Entonces, tu coche rojo va a un caj\u00f3n dentro de la caja 3, y tu osito de peluche va a otro caj\u00f3n dentro de la misma caja 3.\n"
"\n"
"As\u00ed, cuando buscas tu coche rojo, vas a la caja 3 y luego al caj\u00f3n donde sabes que est\u00e1 tu coche. \u00a1Sigue siendo muy r\u00e1pido porque sabes exactamente d\u00f3nde buscar!", None))
        self.btnNext_2.setText(QCoreApplication.translate("StackedWidget", u"Siguiente", None))
        self.label_11.setText(QCoreApplication.translate("StackedWidget", u"TABLAS HASH", None))
        self.label_12.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_18.setText(QCoreApplication.translate("StackedWidget", u"Entonces, queremos acomodar nuestros juguetes en la caja correcta, para eso usaremos nuestra estanteria magica!!", None))
        self.btnNext_3.setText(QCoreApplication.translate("StackedWidget", u"Siguiente", None))
        self.label_21.setText(QCoreApplication.translate("StackedWidget", u"Primero, si metemos nuestro carrito a la estanteria magica nos deberia de mostrar una etiqueta asi:", None))
        self.label_23.setText(QCoreApplication.translate("StackedWidget", u"TABLAS HASH", None))
        self.label_26.setText("")
        self.label_19.setText("")
        self.label_20.setText("")
        self.label_22.setText(QCoreApplication.translate("StackedWidget", u"color: rojo, tipo: carro. caja:1", None))
        self.label_24.setText("")
        self.label_25.setText(QCoreApplication.translate("StackedWidget", u"color: gris, tipo: robot. caja:4", None))
        self.label_27.setText(QCoreApplication.translate("StackedWidget", u"Etiquetas para los demas juguetes", None))
        self.label_28.setText("")
        self.label_29.setText("")
        self.label_30.setText("")
        self.label_31.setText(QCoreApplication.translate("StackedWidget", u"color: azul, tipo: munieco. caja:2", None))
        self.label_32.setText(QCoreApplication.translate("StackedWidget", u"color: cafe, tipo: munieco. caja:2", None))
        self.label_33.setText(QCoreApplication.translate("StackedWidget", u"color: azul rey tipo: consola. caja:3", None))
        self.btnNext_4.setText(QCoreApplication.translate("StackedWidget", u"Siguiente", None))
        self.label_37.setText(QCoreApplication.translate("StackedWidget", u"Como tenemos que guardar al max steel y al oso en la misma caja crearemos una especie de subcaja para guardarlos", None))
        self.label_38.setText(QCoreApplication.translate("StackedWidget", u"Caja 3", None))
        self.label_39.setText("")
        self.label_40.setText("")
        self.label_41.setText(QCoreApplication.translate("StackedWidget", u"Caja 4", None))
        self.label_42.setText(QCoreApplication.translate("StackedWidget", u"TABLAS HASH", None))
        self.label_44.setText(QCoreApplication.translate("StackedWidget", u"Caja 2", None))
        self.label_47.setText(QCoreApplication.translate("StackedWidget", u"Caja 1", None))
        self.label_48.setText("")
        self.label_45.setText("")
        self.label_46.setText("")
        self.label_36.setText("")
        self.label_43.setText("")
        self.label_35.setText("")
        self.label_49.setText("")
        self.label_50.setText(QCoreApplication.translate("StackedWidget", u"De esta Manera cada vez que queramos guardar un nuevo juguete, con nuestra estanteria sabremos donde guardarlo y cuando queramos buscar uno en especial, sabremos donde esta", None))
        self.btnTerminar.setText(QCoreApplication.translate("StackedWidget", u"Terminar", None))
    # retranslateUi

